### ISSUE TITLE
pip2 and pip3 stopped working morning of 2018.6.13

### ISSUE THREAD

**Issue by tylikcat** [pypa/packaging-problems#166]
Errors are:

Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    from pip import main
ImportError: cannot import name main
 
and

Traceback (most recent call last):
  File "/usr/bin/pip3", line 9, in <module>
    from pip import main
ImportError: cannot import name 'main'

respectively.

I've tried ripping out and reinstalling everything, and it all seemed to be working last night. I'm on a fairly vanilla version of Kubuntu, and update frequently.

**Comment by ewdurbin** [comment]
This seems to be a similar issue to https://github.com/pypa/pip/issues/5221 regarding attempting to upgrade pips provided by the system package manager.

You may want to attempt the guidance provided in https://github.com/pypa/pip/issues/5221#issuecomment-382069604 if you attempted to upgrade your system pips `python-pip`/`python3-pip`.

**Comment by merwok** [comment]
This ticket is most probably obsolete @woodruffw
