### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by GalphaXie** [pypa/packaging-problems#303]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?

<Ubuntu 18.04. >

2. What is your Python version?

<Python 3.6.9.>

3. What version of pip do you have?

<pip 9.0.1>

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:

5. Could you describe your issue in as much detail as possible?
when I run `python3 -m twine upload --repository-url https://test.pypi.org/legacy/ dist/*`, I got errors following:
Traceback (most recent call last):
  File "/home/xxx/.local/lib/python3.6/site-packages/keyring/backend.py", line 203, in _load_plugins
    init_func = ep.load()
  File "/home/xxx/.local/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 94, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/keyrings/alt/Windows.py", line 9, in <module>
    from . import file_base
  File "/usr/lib/python3/dist-packages/keyrings/alt/file_base.py", line 13, in <module>
    from keyring.util.escape import escape as escape_for_ini
ModuleNotFoundError: No module named 'keyring.util.escape'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/xxx/.local/lib/python3.6/site-packages/twine/__main__.py", line 31, in <module>
    sys.exit(main())
  File "/home/xxx/.local/lib/python3.6/site-packages/twine/__main__.py", line 25, in main
    return dispatch(sys.argv[1:])
  File "/home/xxx/.local/lib/python3.6/site-packages/twine/cli.py", line 72, in dispatch
    main = registered_commands[args.command].load()
  File "/home/xxx/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/home/xxx/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/xxx/.local/lib/python3.6/site-packages/twine/commands/upload.py", line 20, in <module>
    from twine import settings
  File "/home/xxx/.local/lib/python3.6/site-packages/twine/settings.py", line 22, in <module>
    from twine import auth
  File "/home/xxx/.local/lib/python3.6/site-packages/twine/auth.py", line 6, in <module>
    import keyring
  File "/home/xxx/.local/lib/python3.6/site-packages/keyring/__init__.py", line 1, in <module>
    from .core import (
  File "/home/xxx/.local/lib/python3.6/site-packages/keyring/core.py", line 192, in <module>
    init_backend()
  File "/home/xxx/.local/lib/python3.6/site-packages/keyring/core.py", line 96, in init_backend
    filter(limit, backend.get_all_keyring()),
  File "/home/xxx/.local/lib/python3.6/site-packages/keyring/util/__init__.py", line 22, in wrapper
    func.always_returns = func(*args, **kwargs)
  File "/home/xxx/.local/lib/python3.6/site-packages/keyring/backend.py", line 216, in get_all_keyring
    _load_plugins()
  File "/home/xxx/.local/lib/python3.6/site-packages/keyring/backend.py", line 207, in _load_plugins
    log.exception("Error initializing plugin %s." % ep)
TypeError: not all arguments converted during string formatting

**Comment by merwok** [comment]
The root issue seems to be in the keyring library. Hopefully it was reported to its developers and fixed.

@woodruffw ticket without recent activity
