### ISSUE TITLE
python3 setup.py sdist bdist_wheel

### ISSUE THREAD

**Issue by ThePengwyn** [pypa/packaging-problems#371]
Traceback (most recent call last):
  File "setup.py", line 15, in <module>
    author_email='matthewg@skyhyve.xyz'
  File "/usr/local/lib/python3.7/dist-packages/setuptools/__init__.py", line 161, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.7/dist-packages/setuptools/command/sdist.py", line 52, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.7/distutils/dist.py", line 983, in run_command
    cmd_obj = self.get_command_obj(command)
  File "/usr/lib/python3.7/distutils/dist.py", line 857, in get_command_obj
    klass = self.get_command_class(command)
  File "/usr/local/lib/python3.7/dist-packages/setuptools/dist.py", line 763, in get_command_class
    ep.require(installer=self.fetch_build_egg)
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 2483, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (Pygments 2.4.2 (/home/pengwyn/.local/lib/python3.7/site-packages), Requirement.parse('Pygments>=2.5.1'))

**Comment by merwok** [comment]
Hello!  Can you give some information about what you’re doing?

**Comment by ThePengwyn** [comment]
following the tutorial on packaging at https://packaging.python.org/tutorials/packaging-projects/

get to the line "python3 setup.py sdist bdist_wheel", then instead of getting files generated as the tutorial says, I get this error

**Comment by merwok** [comment]
Copy your `setup.py` please

**Comment by ThePengwyn** [comment]
from setuptools import setup, find_packages

setup(
    name='SkyHyveLM',
    version='0.1',
    packages=find_packages(exclude=['tests*']),
    license='MIT',
    description='Wrapper for large socket communications',
    long_description=open('README.md').read(),
    install_requires=[

    ],
    url='https://github.com/ThePengwyn/SkyHyveLM',
    author='Matthew Graham',
    author_email='matthewg@skyhyve.xyz'

**Comment by merwok** [comment]
There is nothing in install_requires, so the problem must come from the environment.
You have a version of Pygments installed in ~/.local/lib/python3.7 that conflicts with a dependency of something else.

Can you install pipdeptree and run `pipdeptree -r`?

**Comment by ThePengwyn** [comment]
Ok thanks, I have resolved the issue. I had the most recent version of Pygments installed in /usr/local/lib/python3.7/dist-packages but for some reason had another copy of a deprecated version in ~/.local/lib/python3.7/site-packages/ and the python sys.path command returns ['', '/usr/lib/python37.zip', '/usr/lib/python3.7', '/usr/lib/python3.7/lib-dynload', '/home/pengwyn/.local/lib/python3.7/site-packages', '/usr/local/lib/python3.7/dist-packages', '/usr/lib/python3/dist-packages'] which I am assuming means that it is checking ~/.local/lib/python3.7/site-packages/ before it checks in /usr/local/lib/python3.7/dist-packages

Thanks again
