### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by allen546** [pypa/packaging-problems#382]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?
windows 10

2. What is your Python version?
python 3.8.0

3. What version of pip do you have?
pip 20.2

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:
https://packaging.python.org/tutorials/packaging-projects/#setup-args

5. Could you describe your issue in as much detail as possible?
this is the terminal:
C:\Users\lshom\AppData\Local\Programs\Python\Python38-32\Lib>python -m twine upload --repository testpypi dist/*
Uploading distributions to https://test.pypi.org/legacy/
Enter your username: haha1234346364
Enter your password:
Uploading allen-0.0.1-py3-none-any.whl
  0%|                                                             | 0.00/5.07M [00:00<?, ?B/s]
Traceback (most recent call last):
  File "C:\Users\lshom\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\lshom\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\util\connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\lshom\AppData\Local\Programs\Python\Python38-32\Lib\socket.py", line 914, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11002] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lshom\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\lshom\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "C:\Users\lshom\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\connectionpool.py", line 976, in _validate_conn
    conn.connect()
  File "C:\Users\lshom\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\connection.py", line 308, in connect
    conn = self._new_conn()
  File "C:\Users\lshom\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x04A880D0>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lshom\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\lshom\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\connectionpool.py", line 752, in urlopen
    return self.urlopen(
  File "C:\Users\lshom\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\connectionpool.py", line 752, in urlopen
    return self.urlopen(
  File "C:\Users\lshom\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\connectionpool.py", line 752, in urlopen
    return self.urlopen(
  [Previous line repeated 2 more times]
  File "C:\Users\lshom\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\connectionpool.py", line 724, in urlopen
    retries = retries.increment(
  File "C:\Users\lshom\AppData\Local\Programs\Python\Python38-32\lib\site-packages\urllib3\util\retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='test.pypi.org', port=443): Max retries exceeded with url: /legacy/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x04A880D0>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lshom\AppData\Local\Programs\Python\Python38-32\Lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\lshom\AppData\Local\Programs\Python\Python38-32\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\lshom\AppData\Local\Programs\Python\Python38-32\lib\site-packages\twine\__main__.py", line 53, in <module>
    sys.exit(main())
  File "C:\Users\lshom\AppData\Local\Programs\Python\Python38-32\lib\site-packages\twine\__main__.py", line 28, in main
    result = cli.dispatch(sys.argv[1:])
  File "C:\Users\lshom\AppData\Local\Programs\Python\Python38-32\lib\site-packages\twine\cli.py", line 82, in dispatch
    return main(args.args)
  File "C:\Users\lshom\AppData\Local\Programs\Python\Python38-32\lib\site-packages\twine\commands\upload.py", line 151, in main
    return upload(upload_settings, parsed_args.dists)
  File "C:\Users\lshom\AppData\Local\Programs\Python\Python38-32\lib\site-packages\twine\commands\upload.py", line 104, in upload
    resp = repository.upload(package)
  File "C:\Users\lshom\AppData\Local\Programs\Python\Python38-32\lib\site-packages\twine\repository.py", line 188, in upload
    resp = self._upload(package)
  File "C:\Users\lshom\AppData\Local\Programs\Python\Python38-32\lib\site-packages\twine\repository.py", line 174, in _upload
    resp = self.session.post(
  File "C:\Users\lshom\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Users\lshom\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\lshom\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\lshom\AppData\Local\Programs\Python\Python38-32\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='test.pypi.org', port=443): Max retries exceeded with url: /legacy/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x04A880D0>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed'))

C:\Users\lshom\AppData\Local\Programs\Python\Python38-32\Lib>

no offline guides.
packaging is succesful.

**Comment by uranusjr** [comment]
Looks like your network connection has a DNS resolution problem.

**Comment by pradyunsg** [comment]
Closing due a lack of a response.
