### ISSUE TITLE
SSL module in Python not available

### ISSUE THREAD

**Issue by mcrackin15** [pypa/packaging-problems#383]
1. What is your operating system and version?

Windows 10 x64; on VPN

2. What is your Python version?

Python 3.7.6

3. What version of pip do you have?

pip 20.0.2

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:

N/A

5. Could you describe your issue in as much detail as possible?

Hi all, I've installed Python Anaconda3, and the latest version of PyCharm IDE. I've been having difficulty downloading pypi packages. I've tried googling the issue and it is common, but none of the answers/solutions seem to help me. When I execute 'pip install -v openpyxl' I get this message:

(venv) C:\Users\Matthew.McLeod\PycharmProjects\Helloworld>pip install -v  openpyxl
Non-user install because user site-packages disabled
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Created temporary directory: C:\Users\MATTHE~1.MCL\AppData\Local\Temp\pip-ephem-wheel-cache-z0o645sa
Created temporary directory: C:\Users\MATTHE~1.MCL\AppData\Local\Temp\pip-req-tracker-4ijsg30h
Initialized build tracking at C:\Users\MATTHE~1.MCL\AppData\Local\Temp\pip-req-tracker-4ijsg30h
Created build tracker: C:\Users\MATTHE~1.MCL\AppData\Local\Temp\pip-req-tracker-4ijsg30h
Entered build tracker: C:\Users\MATTHE~1.MCL\AppData\Local\Temp\pip-req-tracker-4ijsg30h
Created temporary directory: C:\Users\MATTHE~1.MCL\AppData\Local\Temp\pip-install-hdvi_vzv
1 location(s) to search for versions of openpyxl:
* https://pypi.org/simple/openpyxl/
Fetching project page and analyzing links: https://pypi.org/simple/openpyxl/
Getting page https://pypi.org/simple/openpyxl/
Found index url https://pypi.org/simple
Looking up "https://pypi.org/simple/openpyxl/" in the cache
Request header has "max_age" as 0, cache bypassed
Starting new HTTPS connection (1): pypi.org:443
Incremented Retry for (url='/simple/openpyxl/'): Retry(total=4, connect=None, read=None, redirect=None, status=None)
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/openpyxl/
Starting new HTTPS connection (2): pypi.org:443
Incremented Retry for (url='/simple/openpyxl/'): Retry(total=3, connect=None, read=None, redirect=None, status=None)
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/openpyxl/
Starting new HTTPS connection (3): pypi.org:443
Incremented Retry for (url='/simple/openpyxl/'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/openpyxl/
Starting new HTTPS connection (4): pypi.org:443
Incremented Retry for (url='/simple/openpyxl/'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/openpyxl/
Starting new HTTPS connection (5): pypi.org:443
Incremented Retry for (url='/simple/openpyxl/'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/openpyxl/
Starting new HTTPS connection (6): pypi.org:443
Could not fetch URL https://pypi.org/simple/openpyxl/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/openpyxl/ (Caused by SSLError("Can't conn
ect to HTTPS URL because the SSL module is not available.")) - skipping
Given no hashes to check 0 links for project 'openpyxl': discarding no candidates
ERROR: Could not find a version that satisfies the requirement openpyxl (from versions: none)
Cleaning up...
Removed build tracker: 'C:\\Users\\MATTHE~1.MCL\\AppData\\Local\\Temp\\pip-req-tracker-4ijsg30h'
ERROR: No matching distribution found for openpyxl
Exception information:
Traceback (most recent call last):
  File "c:\users\matthew.mcleod\pycharmprojects\helloworld\venv\lib\site-packages\pip\_internal\cli\base_command.py", line 186, in _main
    status = self.run(options, args)
  File "c:\users\matthew.mcleod\pycharmprojects\helloworld\venv\lib\site-packages\pip\_internal\commands\install.py", line 331, in run
    resolver.resolve(requirement_set)
  File "c:\users\matthew.mcleod\pycharmprojects\helloworld\venv\lib\site-packages\pip\_internal\legacy_resolve.py", line 177, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "c:\users\matthew.mcleod\pycharmprojects\helloworld\venv\lib\site-packages\pip\_internal\legacy_resolve.py", line 333, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "c:\users\matthew.mcleod\pycharmprojects\helloworld\venv\lib\site-packages\pip\_internal\legacy_resolve.py", line 281, in _get_abstract_dist_for
    req.populate_link(self.finder, upgrade_allowed, require_hashes)
  File "c:\users\matthew.mcleod\pycharmprojects\helloworld\venv\lib\site-packages\pip\_internal\req\req_install.py", line 249, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "c:\users\matthew.mcleod\pycharmprojects\helloworld\venv\lib\site-packages\pip\_internal\index\package_finder.py", line 927, in find_requirement
    'No matching distribution found for %s' % req
pip._internal.exceptions.DistributionNotFound: No matching distribution found for openpyxl
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
1 location(s) to search for versions of pip:
* https://pypi.org/simple/pip/
Fetching project page and analyzing links: https://pypi.org/simple/pip/
Getting page https://pypi.org/simple/pip/
Found index url https://pypi.org/simple
Looking up "https://pypi.org/simple/pip/" in the cache
Request header has "max_age" as 0, cache bypassed
Starting new HTTPS connection (1): pypi.org:443
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTT
PS URL because the SSL module is not available.")) - skipping
Given no hashes to check 0 links for project 'pip': discarding no candidates

I have also tried setting proxies for the VPN and set 'pip --proxy [URL] install openpyxl' and it gets the same error.

Thanks in advance!

**Comment by uranusjr** [comment]
How did you install your Python 3.7.6?

**Comment by mcrackin15** [comment]
> How did you install your Python 3.7.6?

**anaconda.com** individual installer

**Comment by uranusjr** [comment]
It’s most likely you’re configuring your environment incorrectly. See pypa/pip#8473 for more context and links to various solutions.
