### ISSUE TITLE
ERROR: No matching distribution found for dataIngest (from modelling2===0.11.20-builder.b0c6266869e4137a139af69412ee729e98cc9ddf)

### ISSUE THREAD

**Issue by pabloa** [pypa/packaging-problems#385]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?

Ubuntu 16.04

2. What is your Python version?

Python 2.7.12

3. What version of pip do you have?

pip 20.2.1 from /home/builder/jenkins/workspace/deploys/he-deploy-lb2/virt-python/local/lib/python2.7/site-packages/pip (python 2.7)

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:

no tutorial

5. Could you describe your issue in as much detail as possible?

I created a virtual environment with thefollowing packages:
```
$ pip list
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Package                            Version                                                  Location
---------------------------------- -------------------------------------------------------- -----------------------------------------------------------------------
aadict                             0.2.3
apispec                            0.35.0
argcomplete                        1.12.0
asset                              0.6.13
awscli                             1.18.114
backports.functools-lru-cache      1.6.1
backports.shutil-get-terminal-size 1.0.0
bcrypt                             3.1.7
boto                               2.49.0
boto3                              1.14.37
botocore                           1.17.37
cachetools                         2.1.0
certifi                            2020.6.20
cffi                               1.14.1
chardet                            3.0.4
click                              7.1.2
colorama                           0.4.3
configparser                       4.0.2
contextlib2                        0.6.0.post1
cryptography                       3.0
cycler                             0.10.0
Cython                             0.28.3
cytoolz                            0.10.1
dataIngest                         1.0.0                                                    /home/builder/jenkins/workspace/deploys/he-deploy-lb2/lb/dataIngest
decorator                          4.4.2
dill                               0.3.2
diskcache                          4.1.0
docutils                           0.15.2
ecdsa                              0.15
enum34                             1.1.10
Flask                              0.12.2
flask-apispec                      0.6.0.post0
Flask-Compress                     1.4.0
Flask-Cors                         3.0.3
flask-swagger-ui                   3.20.9
Flask-Testing                      0.7.1
funcsigs                           1.0.2
futures                            3.3.0
fuzzywuzzy                         0.15.0
globre                             0.1.5
graphyte                           1.6.0
html5lib                           0.9999999
idna                               2.10
importlib-metadata                 1.7.0
ipaddress                          1.0.23
ipdb                               0.13.3
ipython                            5.10.0
ipython-genutils                   0.2.0
itsdangerous                       1.1.0
jedi                               0.9.0
Jinja2                             2.11.2
jmespath                           0.10.0
joblib                             0.11
language-tags                      0.4.3
llvmlite                           0.31.0
lxml                               4.5.2
Markdown                           3.1.1
MarkupSafe                         1.1.1
marshmallow                        3.0.0b12
matplotlib                         2.1.0
modelling2                         0.11.20-builder.b0c6266869e4137a139af69412ee729e98cc9ddf /home/builder/jenkins/workspace/deploys/he-deploy-lb2/lb/modelling2
mpmath                             1.1.0
multiprocess                       0.70.4
munch                              2.5.0
numba                              0.47.0
numexpr                            2.7.1
numpy                              1.16.1
paho-mqtt                          1.5.0
pandas                             0.24.2
paramiko                           2.4.1
parsimonious                       0.8.1
pathlib2                           2.3.5
pathtools                          0.1.2
patsy                              0.5.1
pexpect                            4.8.0
pickleshare                        0.7.5
pika                               0.11.2
pip                                20.2.1
pkg-resources                      0.0.0
prompt-toolkit                     1.0.18
protobuf                           3.12.4
psutil                             5.7.2
psycopg2-binary                    2.8.5
ptyprocess                         0.6.0
pyasn1                             0.4.8
pycfg                              0.0.1                                                    /home/builder/jenkins/workspace/deploys/he-deploy-lb2/devops/DevOps/aws
pycparser                          2.20
pycrypto                           2.6.1
pydevd-pycharm                     192.6603.34
Pygments                           2.5.2
pyhocon                            0.3.55
PyJWT                              1.5.3
PyNaCl                             1.4.0
pyOpenSSL                          19.1.0
pyparsing                          2.4.7
python-dateutil                    2.8.1
python-Levenshtein                 0.12.0
pytz                               2020.1
PyYAML                             5.3.1
redis                              2.10.6
requests                           2.24.0
riemann-client                     6.5.0
rsa                                4.5
s3transfer                         0.3.3
scandir                            1.10.0
scikit-learn                       0.20.4
scipy                              1.2.0
setuptools                         44.0.0
simplegeneric                      0.8.1
singledispatch                     3.4.0.3
six                                1.10.0
SQLAlchemy                         1.3.18
statsmodels                        0.9.0
subprocess32                       3.5.4
sympy                              1.3
tabulate                           0.8.7
toolz                              0.10.0
traitlets                          4.3.3
urllib3                            1.24.1
watchdog                           0.10.2
wcwidth                            0.2.5
webargs                            1.8.1
Werkzeug                           0.16.1
wheel                              0.34.2
zipp                               1.2.0
```

It has 2 packages installed with `pip install -e .`

when I execute the command `pip install -e .`, I get this error:
```
1 location(s) to search for versions of dataIngest:
* https://pypi.org/simple/dataingest/
Fetching project page and analyzing links: https://pypi.org/simple/dataingest/
Getting page https://pypi.org/simple/dataingest/
Found index url https://pypi.org/simple
Looking up "https://pypi.org/simple/dataingest/" in the cache
Request header has "max_age" as 0, cache bypassed
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /simple/dataingest/ HTTP/1.1" 404 13
Status code 404 not in (200, 203, 300, 301)
Could not fetch URL https://pypi.org/simple/dataingest/: 404 Client Error: Not Found for url: https://pypi.org/simple/dataingest/ - skipping
Given no hashes to check 0 links for project 'dataIngest': discarding no candidates
ERROR: Could not find a version that satisfies the requirement dataIngest (from modelling2===0.11.20-builder.b0c6266869e4137a139af69412ee729e98cc9ddf) (from versions: none)
ERROR: No matching distribution found for dataIngest (from modelling2===0.11.20-builder.b0c6266869e4137a139af69412ee729e98cc9ddf)
Exception information:
Traceback (most recent call last):
  File "/home/builder/jenkins/workspace/deploys/he-deploy-lb2/virt-python/local/lib/python2.7/site-packages/pip/_internal/cli/base_command.py", line 216, in _main
    status = self.run(options, args)
  File "/home/builder/jenkins/workspace/deploys/he-deploy-lb2/virt-python/local/lib/python2.7/site-packages/pip/_internal/cli/req_command.py", line 182, in wrapper
    return func(self, options, args)
  File "/home/builder/jenkins/workspace/deploys/he-deploy-lb2/virt-python/local/lib/python2.7/site-packages/pip/_internal/commands/install.py", line 325, in run
    reqs, check_supported_wheels=not options.target_dir
  File "/home/builder/jenkins/workspace/deploys/he-deploy-lb2/virt-python/local/lib/python2.7/site-packages/pip/_internal/resolution/legacy/resolver.py", line 183, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/home/builder/jenkins/workspace/deploys/he-deploy-lb2/virt-python/local/lib/python2.7/site-packages/pip/_internal/resolution/legacy/resolver.py", line 388, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/home/builder/jenkins/workspace/deploys/he-deploy-lb2/virt-python/local/lib/python2.7/site-packages/pip/_internal/resolution/legacy/resolver.py", line 339, in _get_abstract_dist_for
    self._populate_link(req)
  File "/home/builder/jenkins/workspace/deploys/he-deploy-lb2/virt-python/local/lib/python2.7/site-packages/pip/_internal/resolution/legacy/resolver.py", line 305, in _populate_link
    req.link = self._find_requirement_link(req)
  File "/home/builder/jenkins/workspace/deploys/he-deploy-lb2/virt-python/local/lib/python2.7/site-packages/pip/_internal/resolution/legacy/resolver.py", line 270, in _find_requirement_link
    best_candidate = self.finder.find_requirement(req, upgrade)
  File "/home/builder/jenkins/workspace/deploys/he-deploy-lb2/virt-python/local/lib/python2.7/site-packages/pip/_internal/index/package_finder.py", line 928, in find_requirement
    req)
DistributionNotFound: No matching distribution found for dataIngest (from modelling2===0.11.20-builder.b0c6266869e4137a139af69412ee729e98cc9ddf)
Removed build tracker: '/tmp/pip-req-tracker-6FStUv'
```

It is expected is that it install the packages.

It works OK with pip version 'pip==20.2'

**Comment by uranusjr** [comment]
The error is accurate to point out there is no project named `dataIngest`. pypi.org also shows no results at all when I search it. How did you get that package?

**Comment by pabloa** [comment]
@uranusjr dataIngest is an internal project that is installed with `pip install -e .` in developer mode.

If I run `pip list` I can see the package installed:

```
$ pip list
Package                            Version                                                  Location
---------------------------------- -------------------------------------------------------- -----------------------------------------------------------------------
...
dataIngest                         1.0.0                                                    /home/builder/jenkins/workspace/deploys/he-deploy-lb2/lb/dataIngest
...
```

It seems that pip is looking in the cache or https://pypi.org/simple/dataingest/ before checking the filesystem. Python interpreter finds it if I import it.

**Comment by uranusjr** [comment]
How is `dataIngest` installed? This seems related to pypa/pip#8702. Does this work if you downgrade to `pip<20.2`?

**Comment by pabloa** [comment]
`dataIngest` is installed runnin this commands:
```
cd /path/to/dataIngest
pip install -e .
```

If I downgrade to `pip<=20.2`, then it works correctly.

**Comment by uranusjr** [comment]
Then the above linked issue should be the root of this problem.

**Comment by pabloa** [comment]
yes @uranusjr I think you are right. I believe that pull request should fix this issue too.
