### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'loader' for improperly defined namespace package is hard to debug

### ISSUE THREAD

**Issue by kojiromike** [pypa/packaging-problems#414]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?

macOS 10.15.7

2. What is your Python version?

`Python 3.8.3 `

3. What version of pip do you have?

`20.3`

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:

N/A

5. Could you describe your issue in as much detail as possible?

I have created a very small sample project at https://github.com/kojiromike/example-python-package. Trying to run `tox` in this project creates a wheel, installs that wheel in the .tox/{venv}, and then, before it runs tests, shows this error:

```
Error processing line 1 of /Users/michaelsmith/dev/example/.tox/py38/lib/python3.8/site-packages/app-0.1.dev2+ga2b6e8f.d20201202-py3.8-nspkg.pth:

  Traceback (most recent call last):
    File "/Users/michaelsmith/.pyenv/versions/3.8.3/lib/python3.8/site.py", line 169, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
    File "<frozen importlib._bootstrap>", line 553, in module_from_spec
  AttributeError: 'NoneType' object has no attribute 'loader'

Remainder of file ignored
```

I believe that this is due to a mistake in how I've defined setup.cfg; however, I can't tell exactly what the problem is. I searched the web for potential fixes, and unfortunately most of what I've found says "delete that nspkg.pth file" or "manually modify the nspkg.pth file, adding a newline after the import statements."

Those answers aren't reliable because, in this case, running `tox` recreates the environment, the nspkg.pth file, and the problem.

I think two reasonable actions could be taken to improve this behavior and solve the problem:

1. Describe this problem and the solution explicitly in the packaging documentation.
2. Cause setuptools/pip wheel/etc to fail immediately (preferably with a clear error message) when it can't build a namespaced package correctly. (This is based on my flawed/limited understanding of the problem, though.)

If a change can be made in python directly, causing site.py or importlib to provide a clearer error when `importlib.machinery.PathFinder.find_spec` returns `None` could also help.

**Comment by ishwor2048** [comment]
This is good info, but can you be specific what changes to be applied in site.py?
