### ISSUE TITLE
`python3 -m build` - ERROR Backend operation failed: CalledProcessError - Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by sophiefitzpatrick** [pypa/packaging-problems#437]
1. What is your operating system and version?

Mac 10.15.7 Catalina

2. What is your Python version?

Python 3.7.3

3. What version of pip do you have?

pip 20.3.1

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:

https://packaging.python.org/tutorials/packaging-projects/#generating-distribution-archives
`python3 -m build`

5. Could you describe your issue in as much detail as possible?

File structure:
![image](https://user-images.githubusercontent.com/39190044/107120120-a13bfe00-6883-11eb-84bd-ed0f55e77235.png)

I'm new to pypi packages but have followed the tutorial successfully with a pypi dev login, and all been successful.

Here I've ran `python3 -m pip install --upgrade build` and this has been successful, then I've ran `python3 -m build` and I'm getting an error: full stacktrace:

```
(venv) sophie:~/Dropbox/Programming/marvelcli (main)$ python3 -m build
Collecting setuptools>=42
  Using cached setuptools-53.0.0-py3-none-any.whl (784 kB)
Collecting wheel
  Using cached wheel-0.36.2-py2.py3-none-any.whl (35 kB)
Installing collected packages: wheel, setuptools
Successfully installed setuptools-53.0.0 wheel-0.36.2
WARNING: You are using pip version 20.3.1; however, version 21.0.1 is available.
You should consider upgrading via the '/Users/sophie/Dropbox/Programming/marvelcli/venv/bin/python3 -m pip install --upgrade pip' command.
dyld: Library not loaded: @executable_path/../.Python
  Referenced from: /var/folders/zp/9s587pq55zx27ckv8y40xwc00000gn/T/build-env-dume5h64/bin/python
  Reason: image not found
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/var/folders/zp/9s587pq55zx27ckv8y40xwc00000gn/T/build-env-dume5h64/bin/python', '/Users/sophie/Dropbox/Programming/marvelcli/venv/lib/python3.7/site-packages/pep517/_in_process.py', 'build_sdist', '/var/folders/zp/9s587pq55zx27ckv8y40xwc00000gn/T/tmpfphcqcn6']' died with <Signals.SIGABRT: 6>.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sophie/Dropbox/Programming/marvelcli/venv/lib/python3.7/site-packages/build/__init__.py", line 226, in build
    raise BuildBackendException('Backend operation failed: {!r}'.format(e))
build.BuildBackendException: Backend operation failed: CalledProcessError(-6, ['/var/folders/zp/9s587pq55zx27ckv8y40xwc00000gn/T/build-env-dume5h64/bin/python', '/Users/sophie/Dropbox/Programming/marvelcli/venv/lib/python3.7/site-packages/pep517/_in_process.py', 'build_sdist', '/var/folders/zp/9s587pq55zx27ckv8y40xwc00000gn/T/tmpfphcqcn6'])

ERROR Backend operation failed: CalledProcessError(-6, ['/var/folders/zp/9s587pq55zx27ckv8y40xwc00000gn/T/build-env-dume5h64/bin/python', '/Users/sophie/Dropbox/Programming/marvelcli/venv/lib/python3.7/site-packages/pep517/_in_process.py', 'build_sdist', '/var/folders/zp/9s587pq55zx27ckv8y40xwc00000gn/T/tmpfphcqcn6'])
(venv) sophie:~/Dropbox/Programming/marvelcli (main)$ 
```

And my `setup.py` - for the purpose of posting right now i've scrubbed out the personal details

```
import setuptools

with open("README.md", "r", encoding="utf-8") as fh:
    long_description = fh.read()

setuptools.setup(
    name="marvelapp-cli",
    version="0.0.1",
    author="name",
    author_email="email",
    description="A CLI wrapper for Marvelapp",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/fghjkl",
    packages=setuptools.find_packages(),
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    python_requires='>=3.6',
    entry_points='''
        [console_scripts]
        marvelcli=marvelcli.marvelcli:marvelcli
    ''',
)
```

And the `pyproject.toml`

```
[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"
```

Thanks! Let me know if you need any more info!

**Comment by di** [comment]
Your virtualenv is broken, see https://stackoverflow.com/questions/23233252/broken-references-in-virtualenvs

I would also recommend using [pyenv](https://github.com/pyenv/pyenv#installation) instead of Homebrew's python.

**Comment by sophiefitzpatrick** [comment]
Thanks @di this worked for me!
