### ISSUE TITLE
Trouble following packaging libraries tutorial - error in cmd: python3 -m build

### ISSUE THREAD

**Issue by JohnnyWaker** [pypa/packaging-problems#444]
Hello,

first of all thank you for your help ...

1. What is your operating system and version?

Ubuntu 18.04

2. What is your Python version?

Python 3.8

3. What version of pip do you have?

21.0.1

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:

https://packaging.python.org/tutorials/packaging-projects/

5. Could you describe your issue in as much detail as possible?

When executing the command `python3 -m build`

I get the following message (I do not have setuptools-39 but 53, also tried 51 with the same result):

```Uninstalling setuptools-39.0.1:
  Successfully uninstalled setuptools-39.0.1

Usage:   
  /tmp/build-env-lsc0dq0k/bin/python -m pip install [options] <requirement specifier> [package-index-options] ...
  /tmp/build-env-lsc0dq0k/bin/python -m pip install [options] -r <requirements file> [package-index-options] ...
  /tmp/build-env-lsc0dq0k/bin/python -m pip install [options] [-e] <vcs project url> ...
  /tmp/build-env-lsc0dq0k/bin/python -m pip install [options] [-e] <local project path> ...
  /tmp/build-env-lsc0dq0k/bin/python -m pip install [options] <archive url/path> ...

no such option: --no-warn-script-location
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "venv/lib/python3.8/site-packages/build/__main__.py", line 214, in <module>
    main(sys.argv[1:], 'python -m build')
  File "venv/lib/python3.8/site-packages/build/__main__.py", line 206, in main
    build_package(args.srcdir, outdir, distributions, config_settings, not args.no_isolation, args.skip_dependencies)
  File "venv/lib/python3.8/site-packages/build/__main__.py", line 94, in build_package
    _build_in_isolated_env(builder, outdir, distributions, config_settings)
  File "venv/lib/python3.8/site-packages/build/__main__.py", line 56, in _build_in_isolated_env
    env.install(builder.build_dependencies)
  File "venv/lib/python3.8/site-packages/build/env.py", line 143, in install
    subprocess.check_call(cmd)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/tmp/build-env-lsc0dq0k/bin/python', '-Im', 'pip', 'install', '--no-warn-script-location', '-r', '/tmp/build-reqs-ptybtdyh.txt']' returned non-zero exit status 2.
```

Thank you!

Johnny Walker

**Comment by merwok** [comment]
I think this is a problem in https://github.com/pypa/build that was fixed yesterday.

**Comment by henryiii** [comment]
Not released yet, but yes. https://github.com/pypa/build/pull/229

**Comment by henryiii** [comment]
Fixed in build 0.3.0! Please reopen if there are still issues.

**Comment by deprekate** [comment]
Followed the guide, and also received the above errors. It has not been fixed:
```
$ pip install build --upgrade
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: build in /raid60/homes/home3/katelyn/.local/lib/python3.6/site-packages (0.4.0)
Requirement already satisfied: packaging>=19.0 in /raid60/homes/home3/katelyn/.local/lib/python3.6/site-packages (from build) (20.4)
Requirement already satisfied: importlib-metadata>=0.22 in /raid60/homes/home3/katelyn/.local/lib/python3.6/site-packages (from build) (1.7.0)
Requirement already satisfied: pep517>=0.9.1 in /raid60/homes/home3/katelyn/.local/lib/python3.6/site-packages (from build) (0.10.0)
Requirement already satisfied: toml>=0.10.0 in /raid60/homes/home3/katelyn/.local/lib/python3.6/site-packages (from build) (0.10.2)
Requirement already satisfied: zipp>=0.5 in /raid60/homes/home3/katelyn/.local/lib/python3.6/site-packages (from importlib-metadata>=0.22->build) (3.1.0)
Requirement already satisfied: pyparsing>=2.0.2 in /raid60/homes/home3/katelyn/.local/lib/python3.6/site-packages (from packaging>=19.0->build) (2.4.7)
Requirement already satisfied: six in /raid60/homes/home3/katelyn/.local/lib/python3.6/site-packages (from packaging>=19.0->build) (1.15.0)

$ python3 -m build
Requirement already satisfied: pip>=19.1.0 in /raid60/homes/home3/katelyn/.local/lib/python3.6/site-packages (21.1.2)
Found existing installation: setuptools 57.0.0
Not uninstalling setuptools at /raid60/homes/home3/katelyn/.local/lib/python3.6/site-packages, outside environment /tmp/build-env-fpnl52io
Can't uninstall 'setuptools'. No files were found to uninstall.

Usage:   
  /tmp/build-env-fpnl52io/bin/python -m pip install [options] <requirement specifier> [package-index-options] ...
  /tmp/build-env-fpnl52io/bin/python -m pip install [options] -r <requirements file> [package-index-options] ...
  /tmp/build-env-fpnl52io/bin/python -m pip install [options] [-e] <vcs project url> ...
  /tmp/build-env-fpnl52io/bin/python -m pip install [options] [-e] <local project path> ...
  /tmp/build-env-fpnl52io/bin/python -m pip install [options] <archive url/path> ...

no such option: --use-pep517
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home3/katelyn/.local/lib/python3.6/site-packages/build/__main__.py", line 236, in <module>
    main(sys.argv[1:], 'python -m build')
  File "/home3/katelyn/.local/lib/python3.6/site-packages/build/__main__.py", line 228, in main
    build_package(args.srcdir, outdir, distributions, config_settings, not args.no_isolation, args.skip_dependency_check)
  File "/home3/katelyn/.local/lib/python3.6/site-packages/build/__main__.py", line 105, in build_package
    _build_in_isolated_env(builder, outdir, distributions, config_settings)
  File "/home3/katelyn/.local/lib/python3.6/site-packages/build/__main__.py", line 67, in _build_in_isolated_env
    env.install(builder.build_system_requires)
  File "/home3/katelyn/.local/lib/python3.6/site-packages/build/env.py", line 169, in install
    subprocess.check_call(cmd)
  File "/usr/lib64/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/tmp/build-env-fpnl52io/bin/python', '-Im', 'pip', 'install', '--use-pep517', '--no-warn-script-location', '-r', '/tmp/build-reqs-ker3mh1t.txt']' returned non-zero exit status 2.
```

**Comment by Souvic** [comment]
same error received.. not fixed at all!
