### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by skagraw2** [pypa/packaging-problems#446]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?
Windows 10

2. What is your Python version?
3.6.0

3. What version of pip do you have?
pip 21.0.1

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:
https://packaging.python.org/

5. Could you describe your issue in as much detail as possible?
```
myrootfolder\example-py-pkg>python -m build
Collecting pip
  Using cached https://files.pythonhosted.org/packages/fe/ef/60d7ba03b5c442309ef42e7d69959f73aacccd0d86008362a681c4698e83/pip-21.0.1-py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 9.0.1
    Uninstalling pip-9.0.1:
      Successfully uninstalled pip-9.0.1
Successfully installed pip-21.0.1
Found existing installation: setuptools 28.8.0
Uninstalling setuptools-28.8.0:
  Successfully uninstalled setuptools-28.8.0
Collecting wheel
  Using cached wheel-0.36.2-py2.py3-none-any.whl (35 kB)
Collecting setuptools>=42
  Using cached setuptools-53.0.0-py3-none-any.whl (784 kB)
Installing collected packages: wheel, setuptools
Successfully installed setuptools-53.0.0 wheel-0.36.2
Traceback (most recent call last):
  File "C:\Users\xyz\AppData\Local\Programs\Python\Python36\lib\site-packages\pep517\_in_process.py", line 280, in <module>
    main()
  File "C:\Users\xyz\AppData\Local\Programs\Python\Python36\lib\site-packages\pep517\_in_process.py", line 263, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "C:\Users\xyz\AppData\Local\Programs\Python\Python36\lib\site-packages\pep517\_in_process.py", line 236, in build_sdist
    return backend.build_sdist(sdist_directory, config_settings)
  File "C:\Users\xyz\AppData\Local\Temp\build-env-thm13uya\lib\site-packages\setuptools\build_meta.py", line 222, in build_sdist
    config_settings)
  File "C:\Users\xyz\AppData\Local\Temp\build-env-thm13uya\lib\site-packages\setuptools\build_meta.py", line 205, in _build_with_temp_dir
    tmp_dist_dir, result_extension)
  File "C:\Users\xyz\AppData\Local\Temp\build-env-thm13uya\lib\site-packages\setuptools\build_meta.py", line 104, in _file_with_extension
    file, = matching
ValueError: not enough values to unpack (expected 1, got 0)
Traceback (most recent call last):
  File "C:\Users\xyz\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\xyz\\AppData\\Local\\Temp\\build-env-thm13uya\\Scripts\\python.exe', 'C:\\Users\\xyz\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\pep517\\_in_process.py', 'build_sdist', 'C:\\Users\\xyz\\AppData\\Local\\Temp\\tmp9g2qdm9d']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\xyz\AppData\Local\Programs\Python\Python36\lib\site-packages\build\__init__.py", line 275, in build
    raise BuildBackendException('Backend operation failed: {!r}'.format(e))
build.BuildBackendException: Backend operation failed: CalledProcessError(1, ['C:\\Users\\xyz\\AppData\\Local\\Temp\\build-env-thm13uya\\Scripts\\python.exe', 'C:\\Users\\xyz\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\pep517\\_in_process.py', 'build_sdist', 'C:\\Users\\xyz\\AppData\\Local\\Temp\\tmp9g2qdm9d'])

←[91mERROR←[0m Backend operation failed: CalledProcessError(1, ['C:\\Users\\xyz\\AppData\\Local\\Temp\\build-env-thm13uya\\Scripts\\python.exe', 'C:\\Users\\xyz\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\pep517\\_in_process.py', 'build_sdist', 'C:\\Users\\xyz\\AppData\\Local\\Temp\\tmp9g2qdm9d'])
```

created files as mentioned. cfg, py init license, readme etc
python -m pip install --upgrade build

**Comment by henryiii** [comment]
Is your setup.py empty? Do you have the `packages = find:` line? (two common ways to get this error)

**Comment by henryiii** [comment]
I've tried to help a little with avoiding an empty setup.py  in https://github.com/pypa/packaging.python.org/pull/829
