### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by AmdaUwU** [pypa/packaging-problems#448]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?

Windows 10 20H2

2. What is your Python version?

Python 3.8.5

3. What version of pip do you have?

pip 20.2.4

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:

https://packaging.python.org/tutorials/packaging-projects/

5. Could you describe your issue in as much detail as possible?

Reached the _Generating distribution archives_ section of the tutorial , ran the command  
`python -m build`
got 
```
Collecting setuptools>=42
  Using cached setuptools-53.0.0-py3-none-any.whl (784 kB)
Collecting wheel
  Using cached wheel-0.36.2-py2.py3-none-any.whl (35 kB)
Installing collected packages: wheel, setuptools
Successfully installed setuptools-53.0.0 wheel-0.36.2
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\pep517\_in_process.py", line 280, in <module>
    main()
  File "C:\ProgramData\Anaconda3\lib\site-packages\pep517\_in_process.py", line 263, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "C:\ProgramData\Anaconda3\lib\site-packages\pep517\_in_process.py", line 236, in build_sdist
    return backend.build_sdist(sdist_directory, config_settings)
  File "C:\Users\themr\AppData\Local\Temp\build-env-4shteh69\lib\site-packages\setuptools\build_meta.py", line 220, in build_sdist
    return self._build_with_temp_dir(['sdist', '--formats', 'gztar'],
  File "C:\Users\themr\AppData\Local\Temp\build-env-4shteh69\lib\site-packages\setuptools\build_meta.py", line 204, in _build_with_temp_dir
    result_basename = _file_with_extension(
  File "C:\Users\themr\AppData\Local\Temp\build-env-4shteh69\lib\site-packages\setuptools\build_meta.py", line 104, in _file_with_extension
    file, = matching
ValueError: not enough values to unpack (expected 1, got 0)
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\themr\\AppData\\Local\\Temp\\build-env-4shteh69\\Scripts\\python.exe', 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pep517\\_in_process.py', 'build_sdist', 'C:\\Users\\themr\\AppData\\Local\\Temp\\tmpgsq65ohd']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\build\__init__.py", line 275, in build
    raise BuildBackendException('Backend operation failed: {!r}'.format(e))
build.BuildBackendException: Backend operation failed: CalledProcessError(1, ['C:\\Users\\themr\\AppData\\Local\\Temp\\build-env-4shteh69\\Scripts\\python.exe', 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pep517\\_in_process.py', 'build_sdist', 'C:\\Users\\themr\\AppData\\Local\\Temp\\tmpgsq65ohd'])

ERROR Backend operation failed: CalledProcessError(1, ['C:\\Users\\themr\\AppData\\Local\\Temp\\build-env-4shteh69\\Scripts\\python.exe', 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pep517\\_in_process.py', 'build_sdist', 'C:\\Users\\themr\\AppData\\Local\\Temp\\tmpgsq65ohd'])
```

**Comment by henryiii** [comment]
Is your setup.py empty? Do you have the '
`packages = find:` line? (two common ways to get this error)

**Comment by AmdaUwU** [comment]
My setup.py being empty was indeed the problème. Thank you!
