### ISSUE TITLE
Trouble following packaging libraries tutorial: ModuleNotFoundError 'virtualenv.seed.via_app_data'

### ISSUE THREAD

**Issue by bschoening** [pypa/packaging-problems#449]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?

MacOS BigSur 11.1

2. What is your Python version?

Python 3.7.3

3. What version of pip do you have?

pip 21.0.1 

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:

n/a

5. Could you describe your issue in as much detail as possible?

Following the https://packaging.python.org/tutorials/packaging-projects/

```
% python3 -m build
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/brad/Library/Python/3.7/lib/python/site-packages/build/__main__.py", line 214, in <module>
    main(sys.argv[1:], 'python -m build')
  File "/Users/brad/Library/Python/3.7/lib/python/site-packages/build/__main__.py", line 206, in main
    build_package(args.srcdir, outdir, distributions, config_settings, not args.no_isolation, args.skip_dependencies)
  File "/Users/brad/Library/Python/3.7/lib/python/site-packages/build/__main__.py", line 94, in build_package
    _build_in_isolated_env(builder, outdir, distributions, config_settings)
  File "/Users/brad/Library/Python/3.7/lib/python/site-packages/build/__main__.py", line 52, in _build_in_isolated_env
    with IsolatedEnvBuilder() as env:
  File "/Users/brad/Library/Python/3.7/lib/python/site-packages/build/env.py", line 65, in __enter__
    executable, scripts_dir = _create_isolated_env_virtualenv(self._path)
  File "/Users/brad/Library/Python/3.7/lib/python/site-packages/build/env.py", line 156, in _create_isolated_env_virtualenv
    result = virtualenv.cli_run(cmd, setup_logging=False)
  File "/Users/brad/Library/Python/3.7/lib/python/site-packages/virtualenv/run/__init__.py", line 30, in cli_run
    of_session = session_via_cli(args, options, setup_logging, env)
  File "/Users/brad/Library/Python/3.7/lib/python/site-packages/virtualenv/run/__init__.py", line 48, in session_via_cli
    parser, elements = build_parser(args, options, setup_logging, env)
  File "/Users/brad/Library/Python/3.7/lib/python/site-packages/virtualenv/run/__init__.py", line 75, in build_parser
    SeederSelector(interpreter, parser),
  File "/Users/brad/Library/Python/3.7/lib/python/site-packages/virtualenv/run/plugin/seeders.py", line 8, in __init__
    possible = self.options("virtualenv.seed")
  File "/Users/brad/Library/Python/3.7/lib/python/site-packages/virtualenv/run/plugin/base.py", line 39, in options
    cls._OPTIONS = cls.entry_points_for(key)
  File "/Users/brad/Library/Python/3.7/lib/python/site-packages/virtualenv/run/plugin/base.py", line 18, in entry_points_for
    return OrderedDict((e.name, e.load()) for e in cls.entry_points().get(key, {}))
  File "/Users/brad/Library/Python/3.7/lib/python/site-packages/virtualenv/run/plugin/base.py", line 18, in <genexpr>
    return OrderedDict((e.name, e.load()) for e in cls.entry_points().get(key, {}))
  File "/Users/brad/Library/Python/3.7/lib/python/site-packages/importlib_metadata/__init__.py", line 96, in load
    module = import_module(match.group('module'))
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'virtualenv.seed.via_app_data'
```

**Comment by bschoening** [comment]
I resolved this by switching to python 3.9.  I had 3.9 installed with brew, but terminal was still defaulting to /usr/local/python3 which was python 3.7.  By updating MacOS privacy settings to allow terminal full access to the disk, terminal started using /usr/local/bin/python3 which was the brew installed 3.9.  This fixed the virtualenv issue.
