### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by ruz76** [pypa/packaging-problems#452]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?

Ubuntu 18.04.

2. What is your Python version?

Python 3.6.9

3. What version of pip do you have?

pip 21.0.1

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:

python3 -m build

5. Could you describe your issue in as much detail as possible?

```
python3 -m pip install --upgrade build
apt-get install python3-venv
python3 -m pip install --upgrade pip
python3 -m build

Uninstalling setuptools-39.0.1:
  Successfully uninstalled setuptools-39.0.1

Usage:   
  /tmp/build-env-dyo8bau5/bin/python -m pip install [options] <requirement specifier> [package-index-options] ...
  /tmp/build-env-dyo8bau5/bin/python -m pip install [options] -r <requirements file> [package-index-options] ...
  /tmp/build-env-dyo8bau5/bin/python -m pip install [options] [-e] <vcs project url> ...
  /tmp/build-env-dyo8bau5/bin/python -m pip install [options] [-e] <local project path> ...
  /tmp/build-env-dyo8bau5/bin/python -m pip install [options] <archive url/path> ...

no such option: --no-warn-script-location
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jencek/.local/lib/python3.6/site-packages/build/__main__.py", line 214, in <module>
    main(sys.argv[1:], 'python -m build')
  File "/home/jencek/.local/lib/python3.6/site-packages/build/__main__.py", line 206, in main
    build_package(args.srcdir, outdir, distributions, config_settings, not args.no_isolation, args.skip_dependencies)
  File "/home/jencek/.local/lib/python3.6/site-packages/build/__main__.py", line 94, in build_package
    _build_in_isolated_env(builder, outdir, distributions, config_settings)
  File "/home/jencek/.local/lib/python3.6/site-packages/build/__main__.py", line 56, in _build_in_isolated_env
    env.install(builder.build_dependencies)
  File "/home/jencek/.local/lib/python3.6/site-packages/build/env.py", line 143, in install
    subprocess.check_call(cmd)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/tmp/build-env-dyo8bau5/bin/python', '-Im', 'pip', 'install', '--no-warn-script-location', '-r', '/tmp/build-reqs-saqsuaxk.txt']' returned non-zero exit status 2.
```

**Comment by ruz76** [comment]
Fixed by cloning fixed version of build from https://github.com/pypa/build

**Comment by henryiii** [comment]
@FFY00 we need a new release. :)

**Comment by FFY00** [comment]
Yes, sorry. Been a bit busy. I will tag one now.
