### ISSUE TITLE
ValueError: not enough values to unpack (expected 1, got 0)

### ISSUE THREAD

**Issue by smpurkis** [pypa/packaging-problems#454]
1. What is your operating system and version?
Ubuntu 20.04.2

2. What is your Python version?
Python 3.8.5

3. What version of pip do you have?
pip 21.0.1

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:
Followed main 

5. Could you describe your issue in as much detail as possible?

I'm trying to package a simple set of files, source code, https://github.com/smpurkis/fast_json_normalize.
I managed to package a version yesterday, found https://test.pypi.org/project/fast-json-normalize/0.0.1/ using the main guide https://packaging.python.org/tutorials/packaging-projects/. However, I ran into this error today. 

Running the command: `python3 -m build`
Full log:
```Found existing installation: setuptools 44.0.0
Uninstalling setuptools-44.0.0:
  Successfully uninstalled setuptools-44.0.0
Collecting pytest
  Using cached pytest-6.2.2-py3-none-any.whl (280 kB)
Collecting pandas
  Using cached pandas-1.2.2-cp38-cp38-manylinux1_x86_64.whl (9.7 MB)
Collecting wheel
  Using cached wheel-0.36.2-py2.py3-none-any.whl (35 kB)
Collecting setuptools>=42
  Using cached setuptools-53.0.0-py3-none-any.whl (784 kB)
Collecting pluggy<1.0.0a1,>=0.12
  Using cached pluggy-0.13.1-py2.py3-none-any.whl (18 kB)
Collecting toml
  Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting py>=1.8.2
  Using cached py-1.10.0-py2.py3-none-any.whl (97 kB)
Collecting attrs>=19.2.0
  Using cached attrs-20.3.0-py2.py3-none-any.whl (49 kB)
Collecting packaging
  Using cached packaging-20.9-py2.py3-none-any.whl (40 kB)
Collecting iniconfig
  Using cached iniconfig-1.1.1-py2.py3-none-any.whl (5.0 kB)
Collecting numpy>=1.16.5
  Using cached numpy-1.20.1-cp38-cp38-manylinux2010_x86_64.whl (15.4 MB)
Collecting pytz>=2017.3
  Using cached pytz-2021.1-py2.py3-none-any.whl (510 kB)
Collecting python-dateutil>=2.7.3
  Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting pyparsing>=2.0.2
  Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Collecting six>=1.5
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Installing collected packages: pluggy, toml, py, attrs, pyparsing, packaging, iniconfig, pytest, numpy, pytz, six, python-dateutil, pandas, wheel, setuptools
Successfully installed attrs-20.3.0 iniconfig-1.1.1 numpy-1.20.1 packaging-20.9 pandas-1.2.2 pluggy-0.13.1 py-1.10.0 pyparsing-2.4.7 pytest-6.2.2 python-dateutil-2.8.1 pytz-2021.1 setuptools-53.0.0 six-1.15.0 toml-0.10.2 wheel-0.36.2
Traceback (most recent call last):
  File "/home/sam/PycharmProjects/pypi_folder/clean/lib/python3.8/site-packages/pep517/_in_process.py", line 280, in <module>
    main()
  File "/home/sam/PycharmProjects/pypi_folder/clean/lib/python3.8/site-packages/pep517/_in_process.py", line 263, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/home/sam/PycharmProjects/pypi_folder/clean/lib/python3.8/site-packages/pep517/_in_process.py", line 236, in build_sdist
    return backend.build_sdist(sdist_directory, config_settings)
  File "/tmp/build-env-nq_g1n2y/lib/python3.8/site-packages/setuptools/build_meta.py", line 220, in build_sdist
    return self._build_with_temp_dir(['sdist', '--formats', 'gztar'],
  File "/tmp/build-env-nq_g1n2y/lib/python3.8/site-packages/setuptools/build_meta.py", line 204, in _build_with_temp_dir
    result_basename = _file_with_extension(
  File "/tmp/build-env-nq_g1n2y/lib/python3.8/site-packages/setuptools/build_meta.py", line 104, in _file_with_extension
    file, = matching
ValueError: not enough values to unpack (expected 1, got 0)
Traceback (most recent call last):
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/tmp/build-env-nq_g1n2y/bin/python', '/home/sam/PycharmProjects/pypi_folder/clean/lib/python3.8/site-packages/pep517/_in_process.py', 'build_sdist', '/tmp/tmpsppc7moh']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sam/PycharmProjects/pypi_folder/clean/lib/python3.8/site-packages/build/__init__.py", line 308, in _call_backend
    raise BuildBackendException(exception)
build.BuildBackendException: Backend operation failed: CalledProcessError(1, ['/tmp/build-env-nq_g1n2y/bin/python', '/home/sam/PycharmProjects/pypi_folder/clean/lib/python3.8/site-packages/pep517/_in_process.py', 'build_sdist', '/tmp/tmpsppc7moh'])

ERROR Backend operation failed: CalledProcessError(1, ['/tmp/build-env-nq_g1n2y/bin/python', '/home/sam/PycharmProjects/pypi_folder/clean/lib/python3.8/site-packages/pep517/_in_process.py', 'build_sdist', '/tmp/tmpsppc7moh'])
```

I found this, https://github.com/pypa/packaging-problems/issues/437, with a similar error, so tried making the virtual environment again, with the same result.

(P.S I may have gotten something wrong, I'm very new to making python libraries)

**Comment by layday** [comment]
The issue that you have an empty `setup.py`.   You can either remove it or add the following two lines to it:

```py
import setuptools

setuptools.setup()
```

setuptools should probably raise a more informative error in this case.

**Comment by layday** [comment]
The tutorial has been updated to draw attention to `setup.py`.
