### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by hiphamster** [pypa/packaging-problems#455]
Any help will be greatly appreciated!

1. What is your operating system and version?

`Darwin mac-mini.local 18.7.0 Darwin Kernel Version 18.7.0: Tue Jan 12 22:04:47 PST 2021; root:xnu-4903.278.56~1/RELEASE_X86_64 x86_64`

2. What is your Python version?

`Python 3.9.1`

3. What version of pip do you have?

~~~shell
pip --version
pip 21.0.1 from /Users/alex/.pyenv/versions/3.9.1/envs/sandbox/lib/python3.9/site-packages/pip (python 3.9)
~~~

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:

[packaging libraries tutorial](https://python-packaging-user-guide.readthedocs.io/tutorials/packaging-projects/)

5. Could you describe your issue in as much detail as possible?

Have been following the tutorial, during the build i see a message saying i'm using an outdated PIP, perhaps the correct version is not being found ? 

I am using pyenv with virtualenv. 

~~~shell
pip install -U build                                                                                                                                                                                         <<<
Collecting build
  Using cached build-0.3.0-py2.py3-none-any.whl (13 kB)
Collecting packaging
  Using cached packaging-20.9-py2.py3-none-any.whl (40 kB)
Collecting pep517>=0.9
  Using cached pep517-0.9.1-py2.py3-none-any.whl (18 kB)
Collecting toml
  Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting pyparsing>=2.0.2
  Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Installing collected packages: toml, pyparsing, pep517, packaging, build
Successfully installed build-0.3.0 packaging-20.9 pep517-0.9.1 pyparsing-2.4.7 toml-0.10.2
(sandbox) [1:08:15|21-02-23][alex@mac-mini]~/src/sandbox/python_etc/packaging_tutorial
➜  python -m build
Found existing installation: setuptools 49.2.1
Uninstalling setuptools-49.2.1:
  Successfully uninstalled setuptools-49.2.1
Collecting wheel
  Using cached wheel-0.36.2-py2.py3-none-any.whl (35 kB)
Collecting setuptools>=42
  Using cached setuptools-53.0.0-py3-none-any.whl (784 kB)
Installing collected packages: wheel, setuptools
Successfully installed setuptools-53.0.0 wheel-0.36.2
WARNING: You are using pip version 20.2.3; however, version 21.0.1 is available.
You should consider upgrading via the '/var/folders/rx/55k7t_gn12j7zzbgj3db097m0000gn/T/build-env-be507sm5/bin/python -m pip install --upgrade pip' command.
Traceback (most recent call last):
  File "/Users/alex/.pyenv/versions/sandbox/lib/python3.9/site-packages/pep517/_in_process.py", line 280, in <module>
    main()
  File "/Users/alex/.pyenv/versions/sandbox/lib/python3.9/site-packages/pep517/_in_process.py", line 263, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/Users/alex/.pyenv/versions/sandbox/lib/python3.9/site-packages/pep517/_in_process.py", line 236, in build_sdist
    return backend.build_sdist(sdist_directory, config_settings)
  File "/var/folders/rx/55k7t_gn12j7zzbgj3db097m0000gn/T/build-env-be507sm5/lib/python3.9/site-packages/setuptools/build_meta.py", line 220, in build_sdist
    return self._build_with_temp_dir(['sdist', '--formats', 'gztar'],
  File "/var/folders/rx/55k7t_gn12j7zzbgj3db097m0000gn/T/build-env-be507sm5/lib/python3.9/site-packages/setuptools/build_meta.py", line 204, in _build_with_temp_dir
    result_basename = _file_with_extension(
  File "/var/folders/rx/55k7t_gn12j7zzbgj3db097m0000gn/T/build-env-be507sm5/lib/python3.9/site-packages/setuptools/build_meta.py", line 104, in _file_with_extension
    file, = matching
ValueError: not enough values to unpack (expected 1, got 0)
Traceback (most recent call last):
  File "/Users/alex/.pyenv/versions/3.9.1/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/var/folders/rx/55k7t_gn12j7zzbgj3db097m0000gn/T/build-env-be507sm5/bin/python', '/Users/alex/.pyenv/versions/sandbox/lib/python3.9/site-packages/pep517/_in_process.py', 'build_sdist', '/var/folders/rx/55k7t_gn12j7zzbgj3db097m0000gn/T/tmpcf6nmir_']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/alex/.pyenv/versions/sandbox/lib/python3.9/site-packages/build/__init__.py", line 308, in _call_backend
    raise BuildBackendException(exception)
build.BuildBackendException: Backend operation failed: CalledProcessError(1, ['/var/folders/rx/55k7t_gn12j7zzbgj3db097m0000gn/T/build-env-be507sm5/bin/python', '/Users/alex/.pyenv/versions/sandbox/lib/python3.9/site-packages/pep517/_in_process.py', 'build_sdist', '/var/folders/rx/55k7t_gn12j7zzbgj3db097m0000gn/T/tmpcf6nmir_'])

ERROR Backend operation failed: CalledProcessError(1, ['/var/folders/rx/55k7t_gn12j7zzbgj3db097m0000gn/T/build-env-be507sm5/bin/python', '/Users/alex/.pyenv/versions/sandbox/lib/python3.9/site-packages/pep517/_in_process.py', 'build_sdist', '/var/folders/rx/55k7t_gn12j7zzbgj3db097m0000gn/T/tmpcf6nmir_'])
~~~

**Comment by layday** [comment]
This appears to be the same as https://github.com/pypa/packaging-problems/issues/454#issuecomment-783789920.

**Comment by hiphamster** [comment]
@layday Removing setup.py helped - the process completed successfully, but i still got warnings about PIP being out of date. It appears that another python interpreter is being run from `/var/folders/rx/55k7t_gn12j7zzbgj3db097m0000gn/T/build-env-62ak39vk`...

~~~shell
WARNING: You are using pip version 20.2.3; however, version 21.0.1 is available.
You should consider upgrading via the '/var/folders/rx/55k7t_gn12j7zzbgj3db097m0000gn/T/build-env-62ak39vk/bin/python -m pip install --upgrade pip' command.
~~~

**Comment by henryiii** [comment]
Pip comes from venv, which takes the bundled ensurepip version unless it's known to be too old. If you don't like the warning, I think installing virtualenv will remove the warning by getting pip a different way. I'm not sure we should show that warning by default, though, now that we update pip if it's too old.

**Comment by layday** [comment]
The tutorial has been updated to draw attention to `setup.py`.
