### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by cdredmond** [pypa/packaging-problems#456]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?

Linux raspberrypi 5.10.11-v71

2. What is your Python version?

Python 3.7.3

3. What version of pip do you have?

pip 21.0.1

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:

https://packaging.python.org/tutorials/packaging-projects/  Generating distribution archives 

 python3 -m build

5. Could you describe your issue in as much detail as possible?

Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting pip
  Using cached https://files.pythonhosted.org/packages/fe/ef/60d7ba03b5c442309ef42e7d69959f73aacccd0d86008362a681c4698e83/pip-21.0.1-py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 18.1
    Uninstalling pip-18.1:
      Successfully uninstalled pip-18.1
Successfully installed pip-21.0.1
Found existing installation: setuptools 40.8.0
Uninstalling setuptools-40.8.0:
  Successfully uninstalled setuptools-40.8.0
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting setuptools>=42
  Using cached https://www.piwheels.org/simple/setuptools/setuptools-53.0.0-py3-none-any.whl (784 kB)
Collecting wheel
  Using cached https://www.piwheels.org/simple/wheel/wheel-0.36.2-py2.py3-none-any.whl (35 kB)
Installing collected packages: wheel, setuptools
Successfully installed setuptools-53.0.0 wheel-0.36.2
Traceback (most recent call last):
  File "/usr/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/tmp/build-env-h418yfiq/bin/python', '/home/pi/.local/lib/python3.7/site-packages/pep517/_in_process.py', 'build_sdist', '/tmp/tmpvxy7x23s']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/build/__init__.py", line 308, in _call_backend
    raise BuildBackendException(exception)
build.BuildBackendException: Backend operation failed: CalledProcessError(1, ['/tmp/build-env-h418yfiq/bin/python', '/home/pi/.local/lib/python3.7/site-packages/pep517/_in_process.py', 'build_sdist', '/tmp/tmpvxy7x23s'])

ERROR Backend operation failed: CalledProcessError(1, ['/tmp/build-env-h418yfiq/bin/python', '/home/pi/.local/lib/python3.7/site-packages/pep517/_in_process.py', 'build_sdist', '/tmp/tmpvxy7x23s'])

**Comment by ishaileshmishra** [comment]
Hi any update on this ..?

**Comment by cdredmond** [comment]
No update... yet

**Comment by henryiii** [comment]
There doesn't seem to be any information on why this failed in the traceback. Usually it printouts out while there somewhere. Are you capturing both stderr and stdout? Can we see the setup files (setup.py, setup.cfg, pyproject.toml)?

**Comment by cdredmond** [comment]
I will re-start that computer, and retrieve the setup.py, setup.cfg,
pyproject.toml files. Or, re-do the tutorial to recreate them.
