### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by qfaizan401** [pypa/packaging-problems#460]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?

Windows 10

2. What is your Python version?

Python 3.8.5

3. What version of pip do you have?

pip 20.2.4

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:

https://packaging.python.org/tutorials/packaging-projects/

5. Could you describe your issue in as much detail as possible?

- I am at "Generating distribution archives" part of the official tutorial by packaging.python.org
- I ran this command `python3 -m pip install --upgrade build` and this works perfectly fine.
- After that `python3 -m build` does not work.

Error massage:
![error](https://user-images.githubusercontent.com/47282589/109395152-b2d96880-794c-11eb-8e1f-9c3273cb93cc.png)

```
(base) D:\Faizan\pythonProjects\package_copy_content\package>python3 -m build
Found existing installation: setuptools 49.2.1
Uninstalling setuptools-49.2.1:
  Successfully uninstalled setuptools-49.2.1
Collecting setuptools>=42
  Using cached setuptools-53.1.0-py3-none-any.whl (784 kB)
ERROR: Could not find a version that satisfies the requirement os (from -r C:\Users\REHAN~1.QUR\AppData\Local\Temp\build-reqs-mjz1ae15.txt (line 3)) (from versions:
none)
ERROR: No matching distribution found for os (from -r C:\Users\REHAN~1.QUR\AppData\Local\Temp\build-reqs-mjz1ae15.txt (line 3))
WARNING: You are using pip version 20.2.3; however, version 21.0.1 is available.
You should consider upgrading via the 'C:\Users\REHAN~1.QUR\AppData\Local\Temp\build-env-2hah2qw_\Scripts\python.exe -m pip install --upgrade pip' command.
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2288.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2288.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\rehan.qureshi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\build\__main
__.py", line 214, in <module>
    main(sys.argv[1:], 'python -m build')
  File "C:\Users\rehan.qureshi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\build\__main
__.py", line 206, in main
    build_package(args.srcdir, outdir, distributions, config_settings, not args.no_isolation, args.skip_dependencies)
  File "C:\Users\rehan.qureshi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\build\__main
__.py", line 94, in build_package
    _build_in_isolated_env(builder, outdir, distributions, config_settings)
  File "C:\Users\rehan.qureshi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\build\__main
__.py", line 56, in _build_in_isolated_env
    env.install(builder.build_dependencies)
  File "C:\Users\rehan.qureshi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\build\env.py
", line 168, in install
    subprocess.check_call(cmd)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2288.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\REHAN~1.QUR\\AppData\\Local\\Temp\\build-env-2hah2qw_\\Scripts\\python.exe', '-Im', 'pip', 'install', '--use-pep
517', '--no-warn-script-location', '-r', 'C:\\Users\\REHAN~1.QUR\\AppData\\Local\\Temp\\build-reqs-mjz1ae15.txt']' returned non-zero exit status 1.
```

**Comment by layday** [comment]
It looks like you might have declared `os` as a build dependency. `os` is a module in the standard library and not available from PyPI.

**Comment by qfaizan401** [comment]
> It looks like you might have declared `os` as a build dependency. `os` is a module in the standard library and not available from PyPI.

yes i declared os and shutil as a build dependency. i have to remove it?

**Comment by qfaizan401** [comment]
![Untitled](https://user-images.githubusercontent.com/47282589/109398048-0e5f2280-795c-11eb-9db5-2c678993bbb7.png)

**Comment by henryiii** [comment]
Yes, you can’t get standard library modules from PyPI. They are always present because they are built in. l

**Comment by qfaizan401** [comment]
Thanks @layday  and @henryiii for your reply it solved my problem
