### ISSUE TITLE
Error: Backend operation failed: CalledProcessError

### ISSUE THREAD

**Issue by ishaileshmishra** [pypa/packaging-problems#463]
Packaging Python Projects Error: Backend operation failed: CalledProcessError

1. What is your operating system and version?

     `macOS Big Sur 11.2.2`

2. What is your Python version?

     `Python 3.8.0`

3. What version of pip do you have?

     `pip version 21.0.1`

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:

    [Packaging Python Projects](https://packaging.python.org/tutorials/packaging-projects)

5. Could you describe your issue in as much detail as possible?

```
    Found existing installation: setuptools 47.1.0
    Uninstalling setuptools-47.1.0:
      Successfully uninstalled setuptools-47.1.0
    Collecting setuptools>=40.8.0
      Using cached setuptools-54.1.0-py3-none-any.whl (784 kB)
    Collecting wheel
      Using cached wheel-0.36.2-py2.py3-none-any.whl (35 kB)
    Installing collected packages: setuptools, wheel
    Successfully installed setuptools-54.1.0 wheel-0.36.2
    WARNING: You are using pip version 20.1.1; however, version 21.0.1 is available.
    You should consider upgrading via the '/private/var/folders/qc/8bz1l4vn6nq117n_1yntq7sh0000gn/T/build-env-5h6uy7rr/bin/python -m pip install --upgrade pip' command.
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pep517/_in_process.py", line 280, in <module>
        main()
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pep517/_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pep517/_in_process.py", line 219, in get_requires_for_build_sdist
        return hook(config_settings)
      File "/private/var/folders/qc/8bz1l4vn6nq117n_1yntq7sh0000gn/T/build-env-5h6uy7rr/lib/python3.8/site-packages/setuptools/build_meta.py", line 154, in get_requires_for_build_sdist
        return self._get_build_requires(config_settings, requirements=[])
      File "/private/var/folders/qc/8bz1l4vn6nq117n_1yntq7sh0000gn/T/build-env-5h6uy7rr/lib/python3.8/site-packages/setuptools/build_meta.py", line 130, in _get_build_requires
        self.run_setup()
      File "/private/var/folders/qc/8bz1l4vn6nq117n_1yntq7sh0000gn/T/build-env-5h6uy7rr/lib/python3.8/site-packages/setuptools/build_meta.py", line 253, in run_setup
        super(_BuildMetaLegacyBackend,
      File "/private/var/folders/qc/8bz1l4vn6nq117n_1yntq7sh0000gn/T/build-env-5h6uy7rr/lib/python3.8/site-packages/setuptools/build_meta.py", line 145, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 8, in <module>
        import contentstack
      File "/Users/shaileshmishra/Documents/workspace/contentstack/python/contentstack-python/contentstack/__init__.py", line 14, in <module>
        from .https_connection import HTTPSConnection
      File "/Users/shaileshmishra/Documents/workspace/contentstack/python/contentstack-python/contentstack/https_connection.py", line 12, in <module>
        import requests
    ModuleNotFoundError: No module named 'requests'
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/var/folders/qc/8bz1l4vn6nq117n_1yntq7sh0000gn/T/build-env-5h6uy7rr/bin/python', '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pep517/_in_process.py', 'get_requires_for_build_sdist', '/var/folders/qc/8bz1l4vn6nq117n_1yntq7sh0000gn/T/tmpojhoky22']' returned non-zero exit status 1.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/build/__init__.py", line 241, in get_dependencies
        raise BuildBackendException(e)
    build.BuildBackendException: Backend operation failed: CalledProcessError(1, ['/var/folders/qc/8bz1l4vn6nq117n_1yntq7sh0000gn/T/build-env-5h6uy7rr/bin/python', '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pep517/_in_process.py', 'get_requires_for_build_sdist', '/var/folders/qc/8bz1l4vn6nq117n_1yntq7sh0000gn/T/tmpojhoky22'])
    
    ERROR Backend operation failed: CalledProcessError(1, ['/var/folders/qc/8bz1l4vn6nq117n_1yntq7sh0000gn/T/build-env-5h6uy7rr/bin/python', '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pep517/_in_process.py', 'get_requires_for_build_sdist', '/var/folders/qc/8bz1l4vn6nq117n_1yntq7sh0000gn/T/tmpojhoky22'])
```

**Comment by layday** [comment]
You appear to have an undeclared build dependency, requests, which might be transitive.

**Comment by henryiii** [comment]
You should add `requests` to your pyproject.toml file, since you need it when importing your code. Better yet, if this is just to get a version, find a way to export the version without importing your project.
