### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by kaanozdogru** [pypa/packaging-problems#465]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?
macOS Big Sur

2. What is your Python version?
3.8.5

3. What version of pip do you have?
20.2.4

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:
https://packaging.python.org/tutorials/packaging-projects/

5. Could you describe your issue in as much detail as possible?
I ran:
python3 -m build

output:
```
error: can't copy 'LICENSE.txt': doesn't exist or not a regular file
Traceback (most recent call last):
  File "/Users/kaanozdogru/opt/anaconda3/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/var/folders/kd/1jzhwvrd4zq0vqzg65vf5l8w0000gn/T/build-env-jxck9y55/bin/python', '/Users/kaanozdogru/opt/anaconda3/lib/python3.8/site-packages/pep517/in_process/_in_process.py', 'build_wheel', '/var/folders/kd/1jzhwvrd4zq0vqzg65vf5l8w0000gn/T/tmpaidp3dh0']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kaanozdogru/opt/anaconda3/lib/python3.8/site-packages/build/__init__.py", line 309, in _call_backend
    raise BuildBackendException(exception)
build.BuildBackendException: Backend operation failed: CalledProcessError(1, ['/var/folders/kd/1jzhwvrd4zq0vqzg65vf5l8w0000gn/T/build-env-jxck9y55/bin/python', '/Users/kaanozdogru/opt/anaconda3/lib/python3.8/site-packages/pep517/in_process/_in_process.py', 'build_wheel', '/var/folders/kd/1jzhwvrd4zq0vqzg65vf5l8w0000gn/T/tmpaidp3dh0'])

ERROR Backend operation failed: CalledProcessError(1, ['/var/folders/kd/1jzhwvrd4zq0vqzg65vf5l8w0000gn/T/build-env-jxck9y55/bin/python', '/Users/kaanozdogru/opt/anaconda3/lib/python3.8/site-packages/pep517/in_process/_in_process.py', 'build_wheel', '/var/folders/kd/1jzhwvrd4zq0vqzg65vf5l8w0000gn/T/tmpaidp3dh0'])
```

**Comment by henryiii** [comment]
A) please use a more recent pip on Big Sur. 20.3+ for Intel Big Sur and 21.0.1+ for Apple Silicon Big Sur. Not your problem here, though.
B) do you have a LICENSE.txt file?

**Comment by kaanozdogru** [comment]
Hi, I updated pip using:
pip3 install --upgrade pip
Also, I have a file named LICENSE, not LICENSE.txt.
I get the same error

**Comment by merwok** [comment]
What is your packaging config file?  (setup.py or setup.cfg or pyproject.toml)

Seems like you reference a `LICENSE.txt` file in it that doesn’t exist.

**Comment by merwok** [comment]
No follow-up from OP
