### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by TricolorHen061** [pypa/packaging-problems#467]
1. What is your operating system and version?
Ubuntu 20.04

2. What is your Python version?
Python 3.8.5

3. What version of pip do you have?
pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:

https://packaging.python.org/tutorials/packaging-projects/

5. Could you describe your issue in as much detail as possible?

When I run `python3 -m build`, I get this error:

```Found existing installation: setuptools 44.0.0
Uninstalling setuptools-44.0.0:
  Successfully uninstalled setuptools-44.0.0
Collecting setuptools>=42
  Using cached setuptools-54.1.2-py3-none-any.whl (785 kB)
Collecting wheel
  Using cached wheel-0.36.2-py2.py3-none-any.whl (35 kB)
Installing collected packages: setuptools, wheel
Successfully installed setuptools-54.1.2 wheel-0.36.2
Traceback (most recent call last):
  File "/home/evan/.local/lib/python3.8/site-packages/pep517/in_process/_in_process.py", line 280, in <module>
    main()
  File "/home/evan/.local/lib/python3.8/site-packages/pep517/in_process/_in_process.py", line 263, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/home/evan/.local/lib/python3.8/site-packages/pep517/in_process/_in_process.py", line 236, in build_sdist
    return backend.build_sdist(sdist_directory, config_settings)
  File "/tmp/build-env-ao7idiyf/lib/python3.8/site-packages/setuptools/build_meta.py", line 220, in build_sdist
    return self._build_with_temp_dir(['sdist', '--formats', 'gztar'],
  File "/tmp/build-env-ao7idiyf/lib/python3.8/site-packages/setuptools/build_meta.py", line 204, in _build_with_temp_dir
    result_basename = _file_with_extension(
  File "/tmp/build-env-ao7idiyf/lib/python3.8/site-packages/setuptools/build_meta.py", line 104, in _file_with_extension
    file, = matching
ValueError: not enough values to unpack (expected 1, got 0)
Traceback (most recent call last):
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/tmp/build-env-ao7idiyf/bin/python', '/home/evan/.local/lib/python3.8/site-packages/pep517/in_process/_in_process.py', 'build_sdist', '/tmp/tmpk690smrt']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/evan/.local/lib/python3.8/site-packages/build/__init__.py", line 309, in _call_backend
    raise BuildBackendException(exception)
build.BuildBackendException: Backend operation failed: CalledProcessError(1, ['/tmp/build-env-ao7idiyf/bin/python', '/home/evan/.local/lib/python3.8/site-packages/pep517/in_process/_in_process.py', 'build_sdist', '/tmp/tmpk690smrt'])

ERROR Backend operation failed: CalledProcessError(1, ['/tmp/build-env-ao7idiyf/bin/python', '/home/evan/.local/lib/python3.8/site-packages/pep517/in_process/_in_process.py', 'build_sdist', '/tmp/tmpk690smrt'])
```

**Comment by layday** [comment]
You probably have an empty `setup.py`.  You can either delete it or add the following lines to it:

```py
import setuptools

setuptools.setup()
```

**Comment by TricolorHen061** [comment]
Yup that worked, thanks!
