### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by matteobsu** [pypa/packaging-problems#475]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?

Windows 10

2. What is your Python version?

3.8.5

3. What version of pip do you have?

20.3.3

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:

https://packaging.python.org/tutorials/packaging-projects/

5. Could you describe your issue in as much detail as possible?

```
(base) C:\Users\busi_m\Workspace\neutronimaging\ToFImaging>python -m build
Found existing installation: setuptools 47.1.0
Uninstalling setuptools-47.1.0:
  Successfully uninstalled setuptools-47.1.0
Collecting setuptools>=40.8.0
  Using cached setuptools-54.1.2-py3-none-any.whl (785 kB)
Collecting wheel
  Using cached wheel-0.36.2-py2.py3-none-any.whl (35 kB)
Installing collected packages: setuptools, wheel
Successfully installed setuptools-54.1.2 wheel-0.36.2
WARNING: You are using pip version 20.1.1; however, version 21.0.1 is available.
You should consider upgrading via the 'C:\Users\busi_m\AppData\Local\Temp\build-env-od4i7k93\Scripts\python.exe -m pip install --upgrade pip' command.
Traceback (most recent call last):
  File "C:\Users\busi_m\AppData\Local\Temp\build-env-od4i7k93\lib\site-packages\pkg_resources\_vendor\packaging\requirements.py", line 98, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "C:\Users\busi_m\AppData\Local\Temp\build-env-od4i7k93\lib\site-packages\pkg_resources\_vendor\pyparsing.py", line 1654, in parseString
    raise exc
  File "C:\Users\busi_m\AppData\Local\Temp\build-env-od4i7k93\lib\site-packages\pkg_resources\_vendor\pyparsing.py", line 1644, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "C:\Users\busi_m\AppData\Local\Temp\build-env-od4i7k93\lib\site-packages\pkg_resources\_vendor\pyparsing.py", line 1402, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "C:\Users\busi_m\AppData\Local\Temp\build-env-od4i7k93\lib\site-packages\pkg_resources\_vendor\pyparsing.py", line 3417, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "C:\Users\busi_m\AppData\Local\Temp\build-env-od4i7k93\lib\site-packages\pkg_resources\_vendor\pyparsing.py", line 1402, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "C:\Users\busi_m\AppData\Local\Temp\build-env-od4i7k93\lib\site-packages\pkg_resources\_vendor\pyparsing.py", line 3739, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "C:\Users\busi_m\AppData\Local\Temp\build-env-od4i7k93\lib\site-packages\pkg_resources\_vendor\pyparsing.py", line 1402, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "C:\Users\busi_m\AppData\Local\Temp\build-env-od4i7k93\lib\site-packages\pkg_resources\_vendor\pyparsing.py", line 3400, in parseImpl
    loc, resultlist = self.exprs[0]._parse( instring, loc, doActions, callPreParse=False )
  File "C:\Users\busi_m\AppData\Local\Temp\build-env-od4i7k93\lib\site-packages\pkg_resources\_vendor\pyparsing.py", line 1406, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "C:\Users\busi_m\AppData\Local\Temp\build-env-od4i7k93\lib\site-packages\pkg_resources\_vendor\pyparsing.py", line 2711, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pkg_resources._vendor.pyparsing.ParseException: Expected W:(abcd...) (at char 0), (line:1, col:1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\busi_m\Anaconda3\lib\site-packages\pep517\in_process\_in_process.py", line 280, in <module>
    main()
  File "C:\Users\busi_m\Anaconda3\lib\site-packages\pep517\in_process\_in_process.py", line 263, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "C:\Users\busi_m\Anaconda3\lib\site-packages\pep517\in_process\_in_process.py", line 219, in get_requires_for_build_sdist
    return hook(config_settings)
  File "C:\Users\busi_m\AppData\Local\Temp\build-env-od4i7k93\lib\site-packages\setuptools\build_meta.py", line 154, in get_requires_for_build_sdist
    return self._get_build_requires(config_settings, requirements=[])
  File "C:\Users\busi_m\AppData\Local\Temp\build-env-od4i7k93\lib\site-packages\setuptools\build_meta.py", line 130, in _get_build_requires
    self.run_setup()
  File "C:\Users\busi_m\AppData\Local\Temp\build-env-od4i7k93\lib\site-packages\setuptools\build_meta.py", line 253, in run_setup
    super(_BuildMetaLegacyBackend,
  File "C:\Users\busi_m\AppData\Local\Temp\build-env-od4i7k93\lib\site-packages\setuptools\build_meta.py", line 145, in run_setup
    exec(compile(code, __file__, 'exec'), locals())
  File "setup.py", line 1, in <module>
  File "C:\Users\busi_m\AppData\Local\Temp\build-env-od4i7k93\lib\site-packages\setuptools\__init__.py", line 152, in setup
    _install_setup_requires(attrs)
  File "C:\Users\busi_m\AppData\Local\Temp\build-env-od4i7k93\lib\site-packages\setuptools\__init__.py", line 145, in _install_setup_requires
    dist.parse_config_files(ignore_option_errors=True)
  File "C:\Users\busi_m\AppData\Local\Temp\build-env-od4i7k93\lib\site-packages\setuptools\dist.py", line 717, in parse_config_files
    self._finalize_requires()
  File "C:\Users\busi_m\AppData\Local\Temp\build-env-od4i7k93\lib\site-packages\setuptools\dist.py", line 504, in _finalize_requires
    self._move_install_requirements_markers()
  File "C:\Users\busi_m\AppData\Local\Temp\build-env-od4i7k93\lib\site-packages\setuptools\dist.py", line 543, in _move_install_requirements_markers
    inst_reqs = list(pkg_resources.parse_requirements(spec_inst_reqs))
  File "C:\Users\busi_m\AppData\Local\Temp\build-env-od4i7k93\lib\site-packages\pkg_resources\__init__.py", line 3084, in parse_requirements
    yield Requirement(line)
  File "C:\Users\busi_m\AppData\Local\Temp\build-env-od4i7k93\lib\site-packages\pkg_resources\__init__.py", line 3094, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "C:\Users\busi_m\AppData\Local\Temp\build-env-od4i7k93\lib\site-packages\pkg_resources\_vendor\packaging\requirements.py", line 100, in __init__
    raise InvalidRequirement(
pkg_resources.extern.packaging.requirements.InvalidRequirement: Parse error at "'['": Expected W:(abcd...)
Traceback (most recent call last):
  File "C:\Users\busi_m\Anaconda3\lib\subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\busi_m\\AppData\\Local\\Temp\\build-env-od4i7k93\\Scripts\\python.exe', 'C:\\Users\\busi_m\\Anaconda3\\lib\\site-packages\\pep517\\in_process\\_in_process.py', 'get_requires_for_build_sdist', 'C:\\Users\\busi_m\\AppData\\Local\\Temp\\tmpxq7zgt2q']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\busi_m\Anaconda3\lib\site-packages\build\__init__.py", line 242, in get_dependencies
    raise BuildBackendException(e)
build.BuildBackendException: Backend operation failed: CalledProcessError(1, ['C:\\Users\\busi_m\\AppData\\Local\\Temp\\build-env-od4i7k93\\Scripts\\python.exe', 'C:\\Users\\busi_m\\Anaconda3\\lib\\site-packages\\pep517\\in_process\\_in_process.py', 'get_requires_for_build_sdist', 'C:\\Users\\busi_m\\AppData\\Local\\Temp\\tmpxq7zgt2q'])

[91mERROR[0m Backend operation failed: CalledProcessError(1, ['C:\\Users\\busi_m\\AppData\\Local\\Temp\\build-env-od4i7k93\\Scripts\\python.exe', 'C:\\Users\\busi_m\\Anaconda3\\lib\\site-packages\\pep517\\in_process\\_in_process.py', 'get_requires_for_build_sdist', 'C:\\Users\\busi_m\\AppData\\Local\\Temp\\tmpxq7zgt2q'])

(base) C:\Users\busi_m\Workspace\neutronimaging\ToFImaging>python version
python: can't open file 'version': [Errno 2] No such file or directory
```

**Comment by layday** [comment]
Could you attach or link to your 'setup.py' or 'setup.cfg'?

**Comment by matteobsu** [comment]
Hi @layday  Thanks for the answer.

my setup.cfg is
[metadata]
# replace with your username:
name = tofimaging
version = 0.0.3
author = Matteo Busi
author_email = mbusi2691@gmail.com
description = Library for neutron ToF imaging
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/neutronimaging/ToFImaging
project_urls =
    Bug Tracker = https://github.com/neutronimaging/ToFImaging/issues
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent

[options]
package_dir =
    = PythonModules
packages = find:
python_requires = >=3.6

[options.packages.find]
where = PythonModules

and my pyproject:
[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build-meta"

**Comment by henryiii** [comment]
It's:

```toml
build-backend = "setuptools.build_meta"
```

That's an actual Python module in the string, so "-" is not valid.

**Comment by matteobsu** [comment]
That's embarrassing I don't know how it got there I thought I copy-pasted from the tutorial.

Thanks!

**Comment by matteobsu** [comment]
Sorry for reopening it. I managed to build, upload to pypi and be able to install through pip and then import however, I cannot manage to make in the package requirements for additional modules.

Let us say we want the user to install 'lmfit' together with my package so that he doesn't get error later when trying to import my package

I tried in the setup.cfg to add: 
install_requires=['lmfit'],
py_modules=["lmfit"],

and i also tried to add it to the pyproject.toml to the "requires"

But none of my attempts worked. How would you do that?

**Comment by merwok** [comment]
That sounds contradictory: either you are distributing a module named `lmfit`, or you are depending on a distribution called `lmfit`, but having both doesn’t make sense.

**Comment by matteobsu** [comment]
@merwok  thanks for the answer, yeah that's clear. from reading the tutorial i though it would be install_requires but since it didn't work i tried also py_modules instead just to try.
so to making clear, I'm depending on lmfit, as i said in the intro

**Comment by henryiii** [comment]
I have an example of a NumPy dependency here: https://scikit-hep.org/developer/packaging - that might help? You just need install requires.

**Comment by henryiii** [comment]
Pyproject.toml requires is only a build time requires, it's only needed in pure Python packages to list setuptools and wheel, and anything that you depend on to run your setup.py to make a wheel (not common). For compiled packages, this often includes things like Cython and pybind11, since you need those to build.

**Comment by matteobsu** [comment]
Thank you @henryiii . The issue was the syntax.
I thought by readign the tutorial it would be in the form of:
install_requires=[
      'lmfit'],

or something like that but is instead

install_requires =
     lmfit

**Comment by henryiii** [comment]
If you are curious, the ground truth for the .cfg syntax here is https://setuptools.readthedocs.io/en/latest/userguide/declarative_config.html#specifying-values

Will be nice when we can also specify this in pyproject.toml and won't have to worry about a custom syntax. :)
