### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by xikanfeng2** [pypa/packaging-problems#476]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?

MACOS Big Sur 11.2.3

2. What is your Python version?

Python 3.7.0

3. What version of pip do you have?

pip 21.0.1

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:

https://packaging.python.org/tutorials/packaging-projects/

5. Could you describe your issue in as much detail as possible?

The command `python -m build` produces following error:

```Python
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/k12/Library/Python/3.7/lib/python/site-packages/build/__main__.py", line 214, in <module>
    main(sys.argv[1:], 'python -m build')
  File "/Users/k12/Library/Python/3.7/lib/python/site-packages/build/__main__.py", line 206, in main
    build_package(args.srcdir, outdir, distributions, config_settings, not args.no_isolation, args.skip_dependencies)
  File "/Users/k12/Library/Python/3.7/lib/python/site-packages/build/__main__.py", line 94, in build_package
    _build_in_isolated_env(builder, outdir, distributions, config_settings)
  File "/Users/k12/Library/Python/3.7/lib/python/site-packages/build/__main__.py", line 52, in _build_in_isolated_env
    with IsolatedEnvBuilder() as env:
  File "/Users/k12/Library/Python/3.7/lib/python/site-packages/build/env.py", line 91, in __enter__
    executable, scripts_dir = _create_isolated_env_venv(self._path)
  File "/Users/k12/Library/Python/3.7/lib/python/site-packages/build/env.py", line 203, in _create_isolated_env_venv
    pip_distribution = next(iter(metadata.distributions(name='pip', path=[purelib])))
TypeError: distributions() got an unexpected keyword argument 'name'
```

**Comment by layday** [comment]
Your version of `importlib_metadata` is probably too old.  Can you check what it is with `python -m pip show importlib_metadata`?

**Comment by henryiii** [comment]
Build should likely set a minimum?

**Comment by layday** [comment]
Yeah, it should.  I *think* the version that shipped with 3.8.0 was 0.22 so that should be the minimum for compatibility with the module from the standard library.

**Comment by xikanfeng2** [comment]
I use the following command to update all necessary packages and rebuild the project. It works. Thanks for help.
```bash
python3 -m pip install --user --upgrade setuptools wheel twine
```

**Comment by henryiii** [comment]
How did you get Python 3.7.0? The first release of Python is usually a bit buggy. (At least 3.9.0 was). That's not the Big Sur built-in Python 3.8 so it's weird a third party Python installer would be a .0 version.

Anyway, I would like to have known what version of importlib_resources was broken, but I think we should be setting minimums anyway.
