### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by csalyk** [pypa/packaging-problems#477]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?

macOS 10.14.5 (Mojave)

2. What is your Python version?

Python 3.7.3

3. What version of pip do you have?

pip 19.0.3

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:
I was following this tutorial:
https://packaging.python.org/tutorials/packaging-projects/
and ran into an error when running the command:
python3 -m build

5. Could you describe your issue in as much detail as possible?

I think I followed all of the steps in the tutorial, until I got to the line:
python3 -m build

Then, I received this error:

Traceback (most recent call last):
  File "/Users/cosalyk/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/cosalyk/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/cosalyk/anaconda3/lib/python3.7/site-packages/build/__main__.py", line 214, in <module>
    main(sys.argv[1:], 'python -m build')
  File "/Users/cosalyk/anaconda3/lib/python3.7/site-packages/build/__main__.py", line 206, in main
    build_package(args.srcdir, outdir, distributions, config_settings, not args.no_isolation, args.skip_dependencies)
  File "/Users/cosalyk/anaconda3/lib/python3.7/site-packages/build/__main__.py", line 94, in build_package
    _build_in_isolated_env(builder, outdir, distributions, config_settings)
  File "/Users/cosalyk/anaconda3/lib/python3.7/site-packages/build/__main__.py", line 52, in _build_in_isolated_env
    with IsolatedEnvBuilder() as env:
  File "/Users/cosalyk/anaconda3/lib/python3.7/site-packages/build/env.py", line 91, in __enter__
    executable, scripts_dir = _create_isolated_env_venv(self._path)
  File "/Users/cosalyk/anaconda3/lib/python3.7/site-packages/build/env.py", line 203, in _create_isolated_env_venv
    pip_distribution = next(iter(metadata.distributions(name='pip', path=[purelib])))
AttributeError: module 'importlib_metadata' has no attribute 'distributions'

**Comment by henryiii** [comment]
I think this is a known issue with `importlib_metadata` not being updated if it's already installed but too old. See https://github.com/pypa/build/issues/263. Can you do a `pip list` and see what version you have? _After_ doing that, `pip install --upgrade importlib_metadata` will fix your problem, I expect.

**Comment by henryiii** [comment]
(I will predict you have something less than 1, probably also less than 0.22)

**Comment by csalyk** [comment]
Apparently, my version of importlib_metadata was 0.0.0.  The update fixed
the problem - thank you!

**Comment by henryiii** [comment]
> 0.0.0

Wow, that's impressive. :)

**Comment by layday** [comment]
Thanks for bringing this to our attention - @henryiii has added minimum version requirements to build.
