### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by N3X15** [pypa/packaging-problems#484]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal
```

2. What is your Python version?

```
$ python --version
Python 3.8.5
```

3. What version of pip do you have?

```
$ python -m pip --version
pip 21.0.1 from /home/nexis/vnm/.venv/lib/python3.8/site-packages/pip (python 3.8)
```

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:

https://packaging.python.org/tutorials/packaging-projects/

5. Could you describe your issue in as much detail as possible?

I recently converted my project over to use setup.cfg.  To ensure I was up to the latest standards, I followed the tutorial above.  During execution of `python -m build`, I ran into the following error, which persisted past a reboot and a complete reinstall of the `venv` environment.

```
$ python -m build
Found existing installation: setuptools 44.0.0
Uninstalling setuptools-44.0.0:
  Successfully uninstalled setuptools-44.0.0
Collecting wheel
  Using cached wheel-0.36.2-py2.py3-none-any.whl (35 kB)
Collecting setuptools>=42
  Using cached setuptools-54.2.0-py3-none-any.whl (785 kB)
Installing collected packages: wheel, setuptools
Successfully installed setuptools-54.2.0 wheel-0.36.2
running egg_info
error: [Errno 13] Permission denied
Traceback (most recent call last):
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/tmp/build-env-rhs7tl9f/bin/python', '/home/nexis/vnm/.venv/lib/python3.8/site-packages/pep517/in_process/_in_process.py', 'get_requires_for_build_sdist', '/tmp/tmph3qupm5o']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nexis/vnm/.venv/lib/python3.8/site-packages/build/__init__.py", line 242, in get_dependencies
    raise BuildBackendException(e)
build.BuildBackendException: Backend operation failed: CalledProcessError(1, ['/tmp/build-env-rhs7tl9f/bin/python', '/home/nexis/vnm/.venv/lib/python3.8/site-packages/pep517/in_process/_in_process.py', 'get_requires_for_build_sdist', '/tmp/tmph3qupm5o'])

ERROR Backend operation failed: CalledProcessError(1, ['/tmp/build-env-rhs7tl9f/bin/python', '/home/nexis/vnm/.venv/lib/python3.8/site-packages/pep517/in_process/_in_process.py', 'get_requires_for_build_sdist', '/tmp/tmph3qupm5o'])
```
## setup.cfg
(Yes, I am aware that pinning versions of setuptools/pip is iffy at best.  This project touches on their internals to generate configuration and perform package management.)

```ini
# @generated by vnm (see vnm.yml:/package-info)
[metadata]
name = vnm
version = 0.5.0
license = MIT
author = Rob "N3X15" Nelson
author_email = nexisentertainment@gmail.com
long_description = file: README.md
long_description_content_type = text/markdown
url = https://gitlab.com/N3X15/vnm
project_urls = 
	Issue Tracker=https://gitlab.com/N3X15/vnm/-/issues
classifiers = 
	Programming Language :: Python :: 3
	License :: OSI Approved :: MIT License
	Operating System :: OS Independent

[options]
packages = find:
python_requires = >=3.7
install_requires = 
	pip==21.0.1
	setuptools==54.2.0
	wheel==0.36.2
	ruamel.yaml==0.17.2

[options.entry_points]
console_scripts = 
	vnm = vnm.__main__:main
```

## setup.py
```python
from setuptools import setup
setup()
```

## pyproject.toml

This was added later to try and debug the build issue, so it's incomplete.

```
[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"
```

**Comment by N3X15** [comment]
I should also note that `python setup.py bdist_wheel` and `python setup.py sdist` are also failing.

**Comment by layday** [comment]
Does the `vnm.egg-info` directory exist? Is it executable, is it writable by the script? Is the project directory writable?

**Comment by N3X15** [comment]
> 
> 
> Does the `vnm.egg-info` directory exist?

Welp, I'm an idiot.  Not sure how it happened, but the .egg-info directory wasn't accessible. Nuking it as root, then rebuilding the project as luser fixed it.

Thanks for the help.
