### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by Kiwifuit** [pypa/packaging-problems#486]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?

Windows 10

2. What is your Python version?

Python 3.9.2

3. What version of pip do you have?

Pip 21.0.1

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:

5. Could you describe your issue in as much detail as possible?

I followed [this webpage](https://packaging.python.org/tutorials/packaging-projects/)'s instructions.

The Error I Got (Just gonna add the whole thing here, you might need it):
```
Traceback (most recent call last):
  File "C:\Users\Kiwifruit\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Kiwifruit\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Kiwifruit\AppData\Local\Programs\Python\Python39\lib\site-packages\build\__main__.py", line 214, in <module>
    main(sys.argv[1:], 'python -m build')
  File "C:\Users\Kiwifruit\AppData\Local\Programs\Python\Python39\lib\site-packages\build\__main__.py", line 206, in main
    build_package(args.srcdir, outdir, distributions, config_settings, not args.no_isolation, args.skip_dependencies)
  File "C:\Users\Kiwifruit\AppData\Local\Programs\Python\Python39\lib\site-packages\build\__main__.py", line 94, in build_package
    _build_in_isolated_env(builder, outdir, distributions, config_settings)
  File "C:\Users\Kiwifruit\AppData\Local\Programs\Python\Python39\lib\site-packages\build\__main__.py", line 52, in _build_in_isolated_env
    with IsolatedEnvBuilder() as env:
  File "C:\Users\Kiwifruit\AppData\Local\Programs\Python\Python39\lib\site-packages\build\env.py", line 91, in __enter__
    executable, scripts_dir = _create_isolated_env_venv(self._path)
  File "C:\Users\Kiwifruit\AppData\Local\Programs\Python\Python39\lib\site-packages\build\env.py", line 199, in _create_isolated_env_venv
    venv.EnvBuilder(with_pip=True).create(path)
  File "C:\Users\Kiwifruit\AppData\Local\Programs\Python\Python39\lib\venv\__init__.py", line 75, in create
    self._setup_pip(context)
  File "C:\Users\Kiwifruit\AppData\Local\Programs\Python\Python39\lib\venv\__init__.py", line 298, in _setup_pip
    subprocess.check_output(cmd, stderr=subprocess.STDOUT)
  File "C:\Users\Kiwifruit\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\Kiwifruit\AppData\Local\Programs\Python\Python39\lib\site-packages\run\__init__.py", line 145, in __new__
    process = cls.create_process(command, stdin, cwd=cwd, env=env, shell=shell)
  File "C:\Users\Kiwifruit\AppData\Local\Programs\Python\Python39\lib\site-packages\run\__init__.py", line 121, in create_process
    shlex.split(command),
  File "C:\Users\Kiwifruit\AppData\Local\Programs\Python\Python39\lib\shlex.py", line 315, in split
    return list(lex)
  File "C:\Users\Kiwifruit\AppData\Local\Programs\Python\Python39\lib\shlex.py", line 300, in __next__
    token = self.get_token()
  File "C:\Users\Kiwifruit\AppData\Local\Programs\Python\Python39\lib\shlex.py", line 109, in get_token
    raw = self.read_token()
  File "C:\Users\Kiwifruit\AppData\Local\Programs\Python\Python39\lib\shlex.py", line 140, in read_token
    nextchar = self.instream.read(1)
AttributeError: 'list' object has no attribute 'read'
```

And that's pretty much all I can say, I guess

**Comment by merwok** [comment]
Can you describe the layout of your code files and copy the contents of your packaging files (pyproject.toml and other)?

**Comment by merwok** [comment]
There is something very strange in that environment: we see subprocess call a third-party function! (see `site-packages/run/__init__.py`)

There was no follow-up by OP, so closing for now.
