### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by andreasma** [pypa/packaging-problems#487]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?

openSuSE 15.2 - 64bit

2. What is your Python version?

Python 3.6.12

3. What version of pip do you have?

pip 21.0.1

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:

https://github.com/andreasma/liboextensioncreator

5. Could you describe your issue in as much detail as possible?

I added a subdirectory src/liboextensioncreator to the project. I copied all source files and directories to this subdirectory, which got also an empty  __init__.py file. Then I created setup.cfg and setup.py and added the data for my project to them. I added also a pyproject.toml to my project. The README file is in rst file format.
I installed build with the command from the package guide in my virtual env for the package. Once I run python3 -m build I get the following traceback:

python3 -m build
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/(...)/githubrepos_sonstige/liboextensioncreator/lib/python3.6/site-packages/build/__main__.py", line 214, in <module>
    main(sys.argv[1:], 'python -m build')
  File "/home/(...)/githubrepos_sonstige/liboextensioncreator/lib/python3.6/site-packages/build/__main__.py", line 206, in main
    build_package(args.srcdir, outdir, distributions, config_settings, not args.no_isolation, args.skip_dependencies)
  File "/home/(...)/githubrepos_sonstige/liboextensioncreator/lib/python3.6/site-packages/build/__main__.py", line 94, in build_package
    _build_in_isolated_env(builder, outdir, distributions, config_settings)
  File "/home/(...)/githubrepos_sonstige/liboextensioncreator/lib/python3.6/site-packages/build/__main__.py", line 52, in _build_in_isolated_env
    with IsolatedEnvBuilder() as env:
  File "/home/(...)/githubrepos_sonstige/liboextensioncreator/lib/python3.6/site-packages/build/env.py", line 91, in __enter__
    executable, scripts_dir = _create_isolated_env_venv(self._path)
  File "/home/(...)/githubrepos_sonstige/liboextensioncreator/lib/python3.6/site-packages/build/env.py", line 203, in _create_isolated_env_venv
    pip_distribution = next(iter(metadata.distributions(name='pip', path=[purelib])))
StopIteration

**Comment by matthewfeickert** [comment]
Hi @andreasma. I'm able to build a wheel from your library just fine in a Docker image (so I won't be creating a dev virtual environment as the Docker container acts as that here

```
$ docker pull python:3.6
$ docker run --rm -ti python:3.6 /bin/bash
# python --version --version
Python 3.6.13 (default, Apr  2 2021, 23:08:33) 
[GCC 8.3.0]
# python -m pip list
Package    Version
---------- -------
pip        21.0.1
setuptools 54.2.0
wheel      0.36.2
# git clone --depth 1 https://github.com/andreasma/liboextensioncreator.git
# cd liboextensioncreator/
# python -m pip install -r requirements.txt
# python -m pip list
Package                   Version
------------------------- -------
altgraph                  0.17
decorator                 5.0.5
importlib-metadata        3.10.0
pip                       21.0.1
pyinstaller               4.2
pyinstaller-hooks-contrib 2021.1
PyQt5                     5.15.4
PyQt5-Qt5                 5.15.2
PyQt5-sip                 12.8.1
PySide2                   5.15.2
setuptools                54.2.0
shiboken2                 5.15.2
six                       1.15.0
typing-extensions         3.7.4.3
validators                0.18.2
wheel                     0.36.2
zipp                      3.4.1
# python -m pip install build
# python -m build --sdist --wheel --outdir dist/ .  # Note here I'm going to print out all the output for reference
Collecting pip
  Downloading https://files.pythonhosted.org/packages/fe/ef/60d7ba03b5c442309ef42e7d69959f73aacccd0d86008362a681c4698e83/pip-21.0.1-py3-none-any.whl (1.5MB)
    100% |████████████████████████████████| 1.5MB 5.8MB/s 
Installing collected packages: pip
  Found existing installation: pip 18.1
    Uninstalling pip-18.1:
      Successfully uninstalled pip-18.1
Successfully installed pip-21.0.1
Found existing installation: setuptools 40.6.2
Uninstalling setuptools-40.6.2:
  Successfully uninstalled setuptools-40.6.2
Collecting setuptools>=42
  Using cached setuptools-54.2.0-py3-none-any.whl (785 kB)
Collecting wheel
  Using cached wheel-0.36.2-py2.py3-none-any.whl (35 kB)
Installing collected packages: wheel, setuptools
Successfully installed setuptools-54.2.0 wheel-0.36.2
running egg_info
creating src/liboextensioncreator.egg-info
writing src/liboextensioncreator.egg-info/PKG-INFO
writing dependency_links to src/liboextensioncreator.egg-info/dependency_links.txt
writing top-level names to src/liboextensioncreator.egg-info/top_level.txt
writing manifest file 'src/liboextensioncreator.egg-info/SOURCES.txt'
reading manifest file 'src/liboextensioncreator.egg-info/SOURCES.txt'
writing manifest file 'src/liboextensioncreator.egg-info/SOURCES.txt'
running sdist
running egg_info
writing src/liboextensioncreator.egg-info/PKG-INFO
writing dependency_links to src/liboextensioncreator.egg-info/dependency_links.txt
writing top-level names to src/liboextensioncreator.egg-info/top_level.txt
reading manifest file 'src/liboextensioncreator.egg-info/SOURCES.txt'
writing manifest file 'src/liboextensioncreator.egg-info/SOURCES.txt'
running check
creating liboextensioncreator-0.0.1
creating liboextensioncreator-0.0.1/src
creating liboextensioncreator-0.0.1/src/liboextensioncreator
creating liboextensioncreator-0.0.1/src/liboextensioncreator.egg-info
copying files to liboextensioncreator-0.0.1...
copying README.rst -> liboextensioncreator-0.0.1
copying pyproject.toml -> liboextensioncreator-0.0.1
copying setup.cfg -> liboextensioncreator-0.0.1
copying setup.py -> liboextensioncreator-0.0.1
copying src/liboextensioncreator/__init__.py -> liboextensioncreator-0.0.1/src/liboextensioncreator
copying src/liboextensioncreator/liboextensioncreator.py -> liboextensioncreator-0.0.1/src/liboextensioncreator
copying src/liboextensioncreator.egg-info/PKG-INFO -> liboextensioncreator-0.0.1/src/liboextensioncreator.egg-info
copying src/liboextensioncreator.egg-info/SOURCES.txt -> liboextensioncreator-0.0.1/src/liboextensioncreator.egg-info
copying src/liboextensioncreator.egg-info/dependency_links.txt -> liboextensioncreator-0.0.1/src/liboextensioncreator.egg-info
copying src/liboextensioncreator.egg-info/top_level.txt -> liboextensioncreator-0.0.1/src/liboextensioncreator.egg-info
Writing liboextensioncreator-0.0.1/setup.cfg
Creating tar archive
removing 'liboextensioncreator-0.0.1' (and everything under it)
Collecting pip
  Using cached https://files.pythonhosted.org/packages/fe/ef/60d7ba03b5c442309ef42e7d69959f73aacccd0d86008362a681c4698e83/pip-21.0.1-py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 18.1
    Uninstalling pip-18.1:
      Successfully uninstalled pip-18.1
Successfully installed pip-21.0.1
Found existing installation: setuptools 40.6.2
Uninstalling setuptools-40.6.2:
  Successfully uninstalled setuptools-40.6.2
Collecting setuptools>=42
  Using cached setuptools-54.2.0-py3-none-any.whl (785 kB)
Collecting wheel
  Using cached wheel-0.36.2-py2.py3-none-any.whl (35 kB)
Installing collected packages: wheel, setuptools
Successfully installed setuptools-54.2.0 wheel-0.36.2
running egg_info
writing src/liboextensioncreator.egg-info/PKG-INFO
writing dependency_links to src/liboextensioncreator.egg-info/dependency_links.txt
writing top-level names to src/liboextensioncreator.egg-info/top_level.txt
reading manifest file 'src/liboextensioncreator.egg-info/SOURCES.txt'
writing manifest file 'src/liboextensioncreator.egg-info/SOURCES.txt'
Requirement already satisfied: wheel in /tmp/build-env-ep364xj5/lib/python3.6/site-packages (from -r /tmp/build-reqs-0bs0habc.txt (line 1)) (0.36.2)
running bdist_wheel
running build
running build_py
creating build
creating build/lib
creating build/lib/liboextensioncreator
copying src/liboextensioncreator/liboextensioncreator.py -> build/lib/liboextensioncreator
copying src/liboextensioncreator/__init__.py -> build/lib/liboextensioncreator
installing to build/bdist.linux-x86_64/wheel
running install
running install_lib
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/wheel
creating build/bdist.linux-x86_64/wheel/liboextensioncreator
copying build/lib/liboextensioncreator/liboextensioncreator.py -> build/bdist.linux-x86_64/wheel/liboextensioncreator
copying build/lib/liboextensioncreator/__init__.py -> build/bdist.linux-x86_64/wheel/liboextensioncreator
running install_egg_info
running egg_info
writing src/liboextensioncreator.egg-info/PKG-INFO
writing dependency_links to src/liboextensioncreator.egg-info/dependency_links.txt
writing top-level names to src/liboextensioncreator.egg-info/top_level.txt
reading manifest file 'src/liboextensioncreator.egg-info/SOURCES.txt'
writing manifest file 'src/liboextensioncreator.egg-info/SOURCES.txt'
Copying src/liboextensioncreator.egg-info to build/bdist.linux-x86_64/wheel/liboextensioncreator-0.0.1-py3.6.egg-info
running install_scripts
adding license file "LICENSE" (matched pattern "LICEN[CS]E*")
creating build/bdist.linux-x86_64/wheel/liboextensioncreator-0.0.1.dist-info/WHEEL
creating '/liboextensioncreator/dist/tmp4dzbl3yp/liboextensioncreator-0.0.1-py3-none-any.whl' and adding 'build/bdist.linux-x86_64/wheel' to it
adding 'liboextensioncreator/__init__.py'
adding 'liboextensioncreator/liboextensioncreator.py'
adding 'liboextensioncreator-0.0.1.dist-info/LICENSE'
adding 'liboextensioncreator-0.0.1.dist-info/METADATA'
adding 'liboextensioncreator-0.0.1.dist-info/WHEEL'
adding 'liboextensioncreator-0.0.1.dist-info/top_level.txt'
adding 'liboextensioncreator-0.0.1.dist-info/RECORD'
removing build/bdist.linux-x86_64/wheel
# ls -l dist/  # Look inside the dist dir that was created and see that there is a wheel and sdist
total 32
-rw-r--r-- 1 root root 18074 Apr  5 22:46 liboextensioncreator-0.0.1-py3-none-any.whl
-rw-r--r-- 1 root root  8829 Apr  5 22:46 liboextensioncreator-0.0.1.tar.gz
# python -m pip install dist/liboextensioncreator-0.0.1-py3-none-any.whl  # Install from the wheel as a test
Processing ./dist/liboextensioncreator-0.0.1-py3-none-any.whl
Installing collected packages: liboextensioncreator
Successfully installed liboextensioncreator-0.0.1
# python
Python 3.6.13 (default, Apr  2 2021, 23:08:33) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import liboextensioncreator
>>> dir(liboextensioncreator)
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__'
>>>
```

You mention

> I installed build with the command from the package guide

but you never link to this guide. Can you give a link here?

**Comment by layday** [comment]
Probably the same as https://github.com/pypa/build/issues/266.  You could try installing build with the virtualenv extra: `python -m pip install -U build[virtualenv]`.

**Comment by henryiii** [comment]
@matthewfeickert users are following https://packaging.python.org/tutorials/packaging-projects/

**Comment by matthewfeickert** [comment]
> @matthewfeickert users are following https://packaging.python.org/tutorials/packaging-projects/

Yeah, that was my assumption, but as the Issue template 

> If following an online tutorial or guide, please provide a link to the page or section giving you trouble

wasn't answered I wanted to double check.

..though I guess you knew this for sure as if you click on the link in the "Packaging Python Projects" tutorial note

> Note: If you run into trouble here, please copy the output and file an issue over on [packaging problems](https://github.com/pypa/packaging-problems/issues/new?title=Trouble+following+packaging+libraries+tutorial) and we’ll do our best to help you!

it autopopulates the Issue title. :+1: Clever way to backtrack. :)

**Comment by andreasma** [comment]
> Probably the same as [pypa/build#266](https://github.com/pypa/build/issues/266). You could try installing build with the virtualenv extra: `python -m pip install -U build[virtualenv]`.

Thanks @layday
Once I read the command you recommended I was able to run the build command with success.

**Comment by layday** [comment]
Happy to have helped - I'll close this one now.
