### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by gerie1** [pypa/packaging-problems#492]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?

Windows 10 Pro

2. What is your Python version?

Python 3.9.1

3. What version of pip do you have?

pip 21.0.1

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:

https://packaging.python.org/tutorials/packaging-projects/
section: py -m build

5. Could you describe your issue in as much detail as possible?
I ran the command py -m build (upgraded build successfully beforehand) but then an error occurs afterwards:

```
C:\Users\KimHai\packaging_tutorial>py -m build
Found existing installation: setuptools 49.2.1
Uninstalling setuptools-49.2.1:
  Successfully uninstalled setuptools-49.2.1
Collecting setuptools>=42
  Using cached setuptools-56.0.0-py3-none-any.whl (784 kB)
Collecting wheel
  Using cached wheel-0.36.2-py2.py3-none-any.whl (35 kB)
Installing collected packages: setuptools, wheel
Successfully installed setuptools-56.0.0 wheel-0.36.2
WARNING: You are using pip version 20.2.3; however, version 21.0.1 is available.
You should consider upgrading via the 'C:\Users\KimHai\AppData\Local\Temp\build-env-cd_7arqi\Scripts\python.exe -m pip install --upgrade pip' command.
running egg_info
writing src\example_pkg_kdinh.egg-info\PKG-INFO
Traceback (most recent call last):
  File "C:\Users\KimHai\AppData\Local\Programs\Python\Python39\lib\site-packages\pep517\in_process\_in_process.py", line 280, in <module>
    main()
  File "C:\Users\KimHai\AppData\Local\Programs\Python\Python39\lib\site-packages\pep517\in_process\_in_process.py", line 263, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "C:\Users\KimHai\AppData\Local\Programs\Python\Python39\lib\site-packages\pep517\in_process\_in_process.py", line 219, in get_requires_for_build_sdist
    return hook(config_settings)
  File "C:\Users\KimHai\AppData\Local\Temp\build-env-cd_7arqi\lib\site-packages\setuptools\build_meta.py", line 159, in get_requires_for_build_sdist
    return self._get_build_requires(config_settings, requirements=[])
  File "C:\Users\KimHai\AppData\Local\Temp\build-env-cd_7arqi\lib\site-packages\setuptools\build_meta.py", line 135, in _get_build_requires
    self.run_setup()
  File "C:\Users\KimHai\AppData\Local\Temp\build-env-cd_7arqi\lib\site-packages\setuptools\build_meta.py", line 150, in run_setup
    exec(compile(code, __file__, 'exec'), locals())
  File "setup.py", line 6, in <module>
    setuptools.setup(
  File "C:\Users\KimHai\AppData\Local\Temp\build-env-cd_7arqi\lib\site-packages\setuptools\__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\KimHai\AppData\Local\Programs\Python\Python39\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\KimHai\AppData\Local\Programs\Python\Python39\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Users\KimHai\AppData\Local\Programs\Python\Python39\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\KimHai\AppData\Local\Temp\build-env-cd_7arqi\lib\site-packages\setuptools\command\egg_info.py", line 292, in run
    writer(self, ep.name, os.path.join(self.egg_info, ep.name))
  File "C:\Users\KimHai\AppData\Local\Temp\build-env-cd_7arqi\lib\site-packages\setuptools\command\egg_info.py", line 628, in write_pkg_info
    metadata.write_pkg_info(cmd.egg_info)
  File "C:\Users\KimHai\AppData\Local\Programs\Python\Python39\lib\distutils\dist.py", line 1117, in write_pkg_info
    self.write_pkg_file(pkg_info)
  File "C:\Users\KimHai\AppData\Local\Temp\build-env-cd_7arqi\lib\site-packages\setuptools\dist.py", line 167, in write_pkg_file
    for project_url in self.project_urls.items():
AttributeError: 'set' object has no attribute 'items'
Traceback (most recent call last):
  File "C:\Users\KimHai\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\KimHai\\AppData\\Local\\Temp\\build-env-cd_7arqi\\Scripts\\python.exe', 'C:\\Users\\KimHai\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\pep517\\in_process\\_in_process.py', 'get_requires_for_build_sdist', 'C:\\Users\\KimHai\\AppData\\Local\\Temp\\tmpah2capvi']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\KimHai\AppData\Local\Programs\Python\Python39\lib\site-packages\build\__init__.py", line 242, in get_dependencies
    raise BuildBackendException(e)
build.BuildBackendException: Backend operation failed: CalledProcessError(1, ['C:\\Users\\KimHai\\AppData\\Local\\Temp\\build-env-cd_7arqi\\Scripts\\python.exe', 'C:\\Users\\KimHai\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\pep517\\in_process\\_in_process.py', 'get_requires_for_build_sdist', 'C:\\Users\\KimHai\\AppData\\Local\\Temp\\tmpah2capvi'])

←[91mERROR←[0m Backend operation failed: CalledProcessError(1, ['C:\\Users\\KimHai\\AppData\\Local\\Temp\\build-env-cd_7arqi\\Scripts\\python.exe', 'C:\\Users\\KimHai\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\pep517\\in_process\\_in_process.py', 'get_requires_for_build_sdist', 'C:\\Users\\KimHai\\AppData\\Local\\Temp\\tmpah2capvi'])
```

I hope you guys can help me.

**Comment by merwok** [comment]
This is the interesting part of the traceback:
```
File "C:\Users\KimHai\AppData\Local\Temp\build-env-cd_7arqi\lib\site-packages\setuptools\dist.py", line 167, in write_pkg_file
for project_url in self.project_urls.items():
AttributeError: 'set' object has no attribute 'items'
```

What does `project_urls` look like in your config?  It should be a list of `label: url` entries, not solely URLs.

**Comment by gerie1** [comment]
Thanks a lot! It's fixed now.
