### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by vsiddhu** [pypa/packaging-problems#494]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?

Ubuntu 16.04

2. What is your Python version?

Python 3.6.13

3. What version of pip do you have?

pip 21.0.1 from /home/uname/.local/lib/python3.6/site-packages/pip (python 3.6)

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:

https://packaging.python.org/tutorials/packaging-projects/#generating-distribution-archives

5. Could you describe your issue in as much detail as possible?

After completing all previous steps, in the directory containing `pyproject.toml`, I run `python3.6 -m build` and encounter the following error(s) 

```Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/uname/.local/lib/python3.6/site-packages/build/__main__.py", line 214, in <module>
    main(sys.argv[1:], 'python -m build')
  File "/home/uname/.local/lib/python3.6/site-packages/build/__main__.py", line 206, in main
    build_package(args.srcdir, outdir, distributions, config_settings, not args.no_isolation, args.skip_dependencies)
  File "/home/uname/.local/lib/python3.6/site-packages/build/__main__.py", line 94, in build_package
    _build_in_isolated_env(builder, outdir, distributions, config_settings)
  File "/home/uname/.local/lib/python3.6/site-packages/build/__main__.py", line 52, in _build_in_isolated_env
    with IsolatedEnvBuilder() as env:
  File "/home/uname/.local/lib/python3.6/site-packages/build/env.py", line 91, in __enter__
    executable, scripts_dir = _create_isolated_env_venv(self._path)
  File "/home/uname/.local/lib/python3.6/site-packages/build/env.py", line 199, in _create_isolated_env_venv
    venv.EnvBuilder(with_pip=True).create(path)
  File "/usr/lib/python3.6/venv/__init__.py", line 67, in create
    self._setup_pip(context)
  File "/usr/lib/python3.6/venv/__init__.py", line 245, in _setup_pip
    subprocess.check_output(cmd, stderr=subprocess.STDOUT)
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/tmp/build-env-3c_9gwrb/bin/python3.6', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.
```
On attempting to redo the tutorial using a virtual environment, I encounter difficulty at the first step. After running 'python3.6 -m venv tutorial` I encounter an error message similar to the one above,
```
Error: Command '['/home/uname/packaging_tutorial/tutorial/bin/python3.6', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.
```
I'd appreciate any suggestions that may help comlete the tutorial

**Comment by vsiddhu** [comment]
Seems like my Python3.6 installation lacked the `ensurepip` module. This module was installed by running `sudo apt-get install python3.6-venv`, which installs the `venv` module and the `ensurepip` module along with it. These installations, fixed the issue.
