### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by bourgeron** [pypa/packaging-problems#498]
Hello,

I am using Fedora 5.11.12-200.fc33.x86_64, Python 3.9.2, pip 21.0.1 and I am blocked at the build step of https://packaging.python.org/tutorials/packaging-projects/

When typing in python3 -m build, I run into the following error:

ERROR Backend operation failed: CalledProcessError(1, ['/tmp/build-env-s1nk27y2/bin/python', '.local/lib/python3.9/site-packages/pep517/in_process/_in_process.py', 'get_requires_for_build_sdist', '/tmp/tmppvc6m6zl'])

Do you have any clue abour the origin of the problem please?

Thank you very much

**Comment by layday** [comment]
Hi @bourgeron, please paste the complete stack trace.

**Comment by bourgeron** [comment]
python3 -m build

Found existing installation: setuptools 49.1.3
Uninstalling setuptools-49.1.3:
  Successfully uninstalled setuptools-49.1.3
Collecting setuptools>=42
  Using cached setuptools-56.0.0-py3-none-any.whl (784 kB)
Collecting wheel
  Using cached wheel-0.36.2-py2.py3-none-any.whl (35 kB)
Installing collected packages: setuptools, wheel
Successfully installed setuptools-56.0.0 wheel-0.36.2
WARNING: You are using pip version 20.2.2; however, version 21.0.1 is available.
You should consider upgrading via the '/tmp/build-env-4hby8tg7/bin/python -m pip install --upgrade pip' command.
Traceback (most recent call last):
  File ".local/lib/python3.9/site-packages/pep517/in_process/_in_process.py", line 280, in <module>
    main()
  File ".local/lib/python3.9/site-packages/pep517/in_process/_in_process.py", line 263, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File ".local/lib/python3.9/site-packages/pep517/in_process/_in_process.py", line 219, in get_requires_for_build_sdist
    return hook(config_settings)
  File "/tmp/build-env-4hby8tg7/lib64/python3.9/site-packages/setuptools/build_meta.py", line 159, in get_requires_for_build_sdist
    return self._get_build_requires(config_settings, requirements=[])
  File "/tmp/build-env-4hby8tg7/lib64/python3.9/site-packages/setuptools/build_meta.py", line 135, in _get_build_requires
    self.run_setup()
  File "/tmp/build-env-4hby8tg7/lib64/python3.9/site-packages/setuptools/build_meta.py", line 150, in run_setup
    exec(compile(code, __file__, 'exec'), locals())
  File "setup.py", line 1, in <module>
  File "/tmp/build-env-4hby8tg7/lib64/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib64/python3.9/distutils/core.py", line 121, in setup
    dist.parse_config_files()
  File "/tmp/build-env-4hby8tg7/lib64/python3.9/site-packages/setuptools/dist.py", line 715, in parse_config_files
    parse_configuration(self, self.command_options,
  File "/tmp/build-env-4hby8tg7/lib64/python3.9/site-packages/setuptools/config.py", line 152, in parse_configuration
    options.parse()
  File "/tmp/build-env-4hby8tg7/lib64/python3.9/site-packages/setuptools/config.py", line 463, in parse
    section_parser_method(section_options)
  File "/tmp/build-env-4hby8tg7/lib64/python3.9/site-packages/setuptools/config.py", line 436, in parse_section
    self[name] = value
  File "/tmp/build-env-4hby8tg7/lib64/python3.9/site-packages/setuptools/config.py", line 220, in __setitem__
    value = parser(value)
  File "/tmp/build-env-4hby8tg7/lib64/python3.9/site-packages/setuptools/config.py", line 270, in _parse_dict
    raise DistutilsOptionError(
distutils.errors.DistutilsOptionError: Unable to parse option value to dict: src
Traceback (most recent call last):
  File "/usr/lib64/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/tmp/build-env-4hby8tg7/bin/python', '.local/lib/python3.9/site-packages/pep517/in_process/_in_process.py', 'get_requires_for_build_sdist', '/tmp/tmpjckggl8b']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".local/lib/python3.9/site-packages/build/__init__.py", line 242, in get_dependencies
    raise BuildBackendException(e)
build.BuildBackendException: Backend operation failed: CalledProcessError(1, ['/tmp/build-env-4hby8tg7/bin/python', '.local/lib/python3.9/site-packages/pep517/in_process/_in_process.py', 'get_requires_for_build_sdist', '/tmp/tmpjckggl8b'])

ERROR Backend operation failed: CalledProcessError(1, ['/tmp/build-env-4hby8tg7/bin/python', '.local/lib/python3.9/site-packages/pep517/in_process/_in_process.py', 'get_requires_for_build_sdist', '/tmp/tmpjckggl8b'])

**Comment by bourgeron** [comment]
/tmp/build-env-4hby8tg7/bin/python -m pip install --upgrade pip

bash: /tmp/build-env-4hby8tg7/bin/python: No such file or directory

**Comment by bourgeron** [comment]
python -m pip install --upgrade pip

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pip in .local/lib/python3.9/site-packages (21.0.1)

**Comment by layday** [comment]
Of revelevance is:

> distutils.errors.DistutilsOptionError: Unable to parse option value to dict: src

Did you unindent `= src` in your `setup.cfg`?  This option belongs to `package_dir`; you should have:

```cfg
[options]
package_dir =
    = src
```

**Comment by bourgeron** [comment]
Indeed. Thank you very much!

**Comment by layday** [comment]
Happy to help.
