### ISSUE TITLE
Access is denied: 'dist'

### ISSUE THREAD

**Issue by khanbasilMA** [pypa/packaging-problems#500]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?

Window 10

2. What is your Python version?

3.9.4

3. What version of pip do you have?

21.1

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:

python -m build

5. Could you describe your issue in as much detail as possible?

Traceback (most recent call last):
  File "C:\Users\KHanB\scoop\apps\python\current\lib\site-packages\pep517\in_process\_in_process.py", line 280, in <module>
    main()
  File "C:\Users\KHanB\scoop\apps\python\current\lib\site-packages\pep517\in_process\_in_process.py", line 263, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "C:\Users\KHanB\scoop\apps\python\current\lib\site-packages\pep517\in_process\_in_process.py", line 236, in build_sdist
    return backend.build_sdist(sdist_directory, config_settings)
  File "C:\Users\KHanB\AppData\Local\Temp\build-env-pbxappx2\lib\site-packages\setuptools\build_meta.py", line 166, in build_sdist
    shutil.copytree('dist', sdist_directory)
  File "C:\Users\KHanB\scoop\apps\python\current\lib\shutil.py", line 552, in copytree
    with os.scandir(src) as itr:
PermissionError: [WinError 5] Access is denied: 'dist'
Traceback (most recent call last):
  File "C:\Users\KHanB\scoop\apps\python\current\lib\subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\KHanB\\AppData\\Local\\Temp\\build-env-pbxappx2\\Scripts\\python.exe', 'C:\\Users\\KHanB\\scoop\\apps\\python\\current\\lib\\site-packages\\pep517\\in_process\\_in_process.py', 'build_sdist', 'C:\\Users\\KHanB\\AppData\\Local\\Temp\\tmpeiql8ryv']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\KHanB\scoop\apps\python\current\lib\site-packages\build\__init__.py", line 309, in _call_backend
    raise BuildBackendException(exception)
build.BuildBackendException: Backend operation failed: CalledProcessError(1, ['C:\\Users\\KHanB\\AppData\\Local\\Temp\\build-env-pbxappx2\\Scripts\\python.exe', 'C:\\Users\\KHanB\\scoop\\apps\\python\\current\\lib\\site-packages\\pep517\\in_process\\_in_process.py', 'build_sdist', 'C:\\Users\\KHanB\\AppData\\Local\\Temp\\tmpeiql8ryv'])

[91mERROR[0m Backend operation failed: CalledProcessError(1, ['C:\\Users\\KHanB\\AppData\\Local\\Temp\\build-env-pbxappx2\\Scripts\\python.exe', 'C:\\Users\\KHanB\\scoop\\apps\\python\\current\\lib\\site-packages\\pep517\\in_process\\_in_process.py', 'build_sdist', 'C:\\Users\\KHanB\\AppData\\Local\\Temp\\tmpeiql8ryv'])

**Comment by khanbasilMA** [comment]
Also getting 

FileNotFoundError: [WinError 3] The system cannot find the path specified: 'dist'
Traceback (most recent call last):
  File "C:\Users\KHanB\scoop\apps\python\current\lib\subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\KHanB\\AppData\\Local\\Temp\\build-env-yx1ci4tt\\Scripts\\python.exe', 'C:\\Users\\KHanB\\scoop\\apps\\python\\current\\lib\\site-packages\\pep517\\in_process\\_in_process.py', 'build_sdist', 'C:\\Users\\KHanB\\AppData\\Local\\Temp\\tmpjds__z7n']' returned non-zero exit status 1.

**Comment by alexsio27444** [comment]
> Thank you for providing feedback on Python packaging!
> 
> To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.
> 
> 1. What is your operating system and version?
> 
> Window 10
> 
> 2. What is your Python version?
> 
> 3.9.4
> 
> 3. What version of pip do you have?
> 
> 21.1
> 
> 4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:
> 
> python -m build
> 
> 5. Could you describe your issue in as much detail as possible?
> 
> Traceback (most recent call last):
>   File "C:\Users\KHanB\scoop\apps\python\current\lib\site-packages\pep517\in_process\_in_process.py", line 280, in <module>
>     main()
>   File "C:\Users\KHanB\scoop\apps\python\current\lib\site-packages\pep517\in_process\_in_process.py", line 263, in main
>     json_out['return_val'] = hook(**hook_input['kwargs'])
>   File "C:\Users\KHanB\scoop\apps\python\current\lib\site-packages\pep517\in_process\_in_process.py", line 236, in build_sdist
>     return backend.build_sdist(sdist_directory, config_settings)
>   File "C:\Users\KHanB\AppData\Local\Temp\build-env-pbxappx2\lib\site-packages\setuptools\build_meta.py", line 166, in build_sdist
>     shutil.copytree('dist', sdist_directory)
>   File "C:\Users\KHanB\scoop\apps\python\current\lib\shutil.py", line 552, in copytree
>     with os.scandir(src) as itr:
> PermissionError: [WinError 5] Access is denied: 'dist'
> Traceback (most recent call last):
>   File "C:\Users\KHanB\scoop\apps\python\current\lib\subprocess.py", line 373, in check_call
>     raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command '['C:\\Users\\KHanB\\AppData\\Local\\Temp\\build-env-pbxappx2\\Scripts\\python.exe', 'C:\\Users\\KHanB\\scoop\\apps\\python\\current\\lib\\site-packages\\pep517\\in_process\\_in_process.py', 'build_sdist', 'C:\\Users\\KHanB\\AppData\\Local\\Temp\\tmpeiql8ryv']' returned non-zero exit status 1.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\KHanB\scoop\apps\python\current\lib\site-packages\build\__init__.py", line 309, in _call_backend
>     raise BuildBackendException(exception)
> build.BuildBackendException: Backend operation failed: CalledProcessError(1, ['C:\\Users\\KHanB\\AppData\\Local\\Temp\\build-env-pbxappx2\\Scripts\\python.exe', 'C:\\Users\\KHanB\\scoop\\apps\\python\\current\\lib\\site-packages\\pep517\\in_process\\_in_process.py', 'build_sdist', 'C:\\Users\\KHanB\\AppData\\Local\\Temp\\tmpeiql8ryv'])
> 
> [91mERROR[0m Backend operation failed: CalledProcessError(1, ['C:\\Users\\KHanB\\AppData\\Local\\Temp\\build-env-pbxappx2\\Scripts\\python.exe', 'C:\\Users\\KHanB\\scoop\\apps\\python\\current\\lib\\site-packages\\pep517\\in_process\\_in_process.py', 'build_sdist', 'C:\\Users\\KHanB\\AppData\\Local\\Temp\\tmpeiql8ryv'])
>
