### ISSUE TITLE
Build Error: "Check if you installed GEOS engine" Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by Aniwax** [pypa/packaging-problems#507]
# Question: Does GEOS engine hinders the building of python packages?

1. What is your operating system and version?

OSX Catalina 10.15.7, Microsoft Windows 10 Education

2. What is your Python version?

3.7.5

3. What version of pip do you have?

19.2.3

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:

https://packaging.python.org/tutorials/packaging-projects/
<img width="920" alt="Screenshot 2021-05-05 at 14 53 30" src="https://user-images.githubusercontent.com/71446830/117144074-cb815700-adb1-11eb-8c87-03b3147a1b07.png">

5. Could you describe your issue in as much detail as possible?

I was just following the guide to build a dumppy package. I ran into problem with I ran 
`python -m build`. Before this step, everything was smooth. 
The error message I encountered is following:

```
python -m build
Uninstalling setuptools-41.2.0:
  Successfully uninstalled setuptools-41.2.0
Collecting setuptools>=42 (from -r /var/folders/4g/s1b1rk9n7jlgpn5z46j3s62h0000gn/T/build-reqs-2munna9m.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/11/1b/7012b145cb228aed20f9b2b8b259df49e7963d900799ea44791f54d06ab9/setuptools-56.1.0-py3-none-any.whl (785kB)
     |████████████████████████████████| 788kB 7.0MB/s
Collecting wheel (from -r /var/folders/4g/s1b1rk9n7jlgpn5z46j3s62h0000gn/T/build-reqs-2munna9m.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/65/63/39d04c74222770ed1589c0eaba06c05891801219272420b40311cd60c880/wheel-0.36.2-py2.py3-none-any.whl
Installing collected packages: setuptools, wheel
Successfully installed setuptools-56.1.0 wheel-0.36.2
WARNING: You are using pip version 19.2.3, however version 21.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Traceback (most recent call last):
  File "/Users/shirzart/.pyenv/versions/3.7.5/lib/python3.7/site-packages/pep517/in_process/_in_process.py", line 280, in <module>
    main()
  File "/Users/shirzart/.pyenv/versions/3.7.5/lib/python3.7/site-packages/pep517/in_process/_in_process.py", line 263, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/Users/shirzart/.pyenv/versions/3.7.5/lib/python3.7/site-packages/pep517/in_process/_in_process.py", line 219, in get_requires_for_build_sdist
    return hook(config_settings)
  File "/var/folders/4g/s1b1rk9n7jlgpn5z46j3s62h0000gn/T/build-env-sx_97uqg/lib/python3.7/site-packages/setuptools/build_meta.py", line 159, in get_requires_for_build_sdist
    return self._get_build_requires(config_settings, requirements=[])
  File "/var/folders/4g/s1b1rk9n7jlgpn5z46j3s62h0000gn/T/build-env-sx_97uqg/lib/python3.7/site-packages/setuptools/build_meta.py", line 135, in _get_build_requires
    self.run_setup()
  File "/var/folders/4g/s1b1rk9n7jlgpn5z46j3s62h0000gn/T/build-env-sx_97uqg/lib/python3.7/site-packages/setuptools/build_meta.py", line 150, in run_setup
    exec(compile(code, __file__, 'exec'), locals())
  File "setup.py", line 8
    1. Check if you installed GEOS engine
           ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/Users/shirzart/.pyenv/versions/3.7.5/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/var/folders/4g/s1b1rk9n7jlgpn5z46j3s62h0000gn/T/build-env-sx_97uqg/bin/python', '/Users/shirzart/.pyenv/versions/3.7.5/lib/python3.7/site-packages/pep517/in_process/_in_process.py', 'get_requires_for_build_sdist', '/var/folders/4g/s1b1rk9n7jlgpn5z46j3s62h0000gn/T/tmpvaf6pdls']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/shirzart/.pyenv/versions/3.7.5/lib/python3.7/site-packages/build/__init__.py", line 242, in get_dependencies
    raise BuildBackendException(e)
build.BuildBackendException: Backend operation failed: CalledProcessError(1, ['/var/folders/4g/s1b1rk9n7jlgpn5z46j3s62h0000gn/T/build-env-sx_97uqg/bin/python', '/Users/shirzart/.pyenv/versions/3.7.5/lib/python3.7/site-packages/pep517/in_process/_in_process.py', 'get_requires_for_build_sdist', '/var/folders/4g/s1b1rk9n7jlgpn5z46j3s62h0000gn/T/tmpvaf6pdls'])
                                                                                                                            exit:1
```

**Comment by layday** [comment]
It looks like you have text which is not commented out in your `setup.py`.  Try adding a `#` at the start of the line begging with "1. Check".

**Comment by Aniwax** [comment]
@layday Thanks for the reply! 
I indeed solved it by deleting `setup.py`, since I was just using `setup.cfg`. After your comment, I checked again and there was some unorganized content inside `setup.py`, which was not needed.

Though I solved it before I saw your comment, but thanks a lot for your lightening reply!
