### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by Makhmud99** [pypa/packaging-problems#515]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?

Ubuntu 20.04 LTSC

2. What is your Python version?

Python 3.8.5

3. What version of pip do you have?

pip 20.0.2 

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:

5. Could you describe your issue in as much detail as possible?

python -m build
I get the output
(supervenv) i_01001101@pavilion:~/pdp1$ python3 -m build
Found existing installation: setuptools 44.0.0
Uninstalling setuptools-44.0.0:
  Successfully uninstalled setuptools-44.0.0
Collecting wheel
  Using cached wheel-0.36.2-py2.py3-none-any.whl (35 kB)
Collecting setuptools>=42
  Using cached setuptools-56.2.0-py3-none-any.whl (785 kB)
Installing collected packages: wheel, setuptools
Successfully installed setuptools-56.2.0 wheel-0.36.2
running egg_info
error: error in 'egg_base' option: 'src' does not exist or is not a directory
Traceback (most recent call last):
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/tmp/build-env-ygq9qvi5/bin/python', '/home/i_01001101/pdp1/supervenv/lib/python3.8/site-packages/pep517/in_process/_in_process.py', 'get_requires_for_build_sdist', '/tmp/tmpsr1_u18j']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/i_01001101/pdp1/supervenv/lib/python3.8/site-packages/build/__init__.py", line 242, in get_dependencies
    raise BuildBackendException(e)
build.BuildBackendException: Backend operation failed: CalledProcessError(1, ['/tmp/build-env-ygq9qvi5/bin/python', '/home/i_01001101/pdp1/supervenv/lib/python3.8/site-packages/pep517/in_process/_in_process.py', 'get_requires_for_build_sdist', '/tmp/tmpsr1_u18j'])

ERROR Backend operation failed: CalledProcessError(1, ['/tmp/build-env-ygq9qvi5/bin/python', '/home/i_01001101/pdp1/supervenv/lib/python3.8/site-packages/pep517/in_process/_in_process.py', 'get_requires_for_build_sdist', '/tmp/tmpsr1_u18j'])

**Comment by henryiii** [comment]
> 'src' does not exist or is not a directory

Are you using src layout in your configuration but not placing the package in src?

**Comment by henryiii** [comment]
Also, the next version of build should print nicer tracebacks due to @FFY00's recent work.

**Comment by merwok** [comment]
No reply from OP
