### ISSUE TITLE
Trouble following packaging libraries tutorial

### ISSUE THREAD

**Issue by BigIan1969** [pypa/packaging-problems#519]
Thank you for providing feedback on Python packaging!

To help us help you, please fill out as much of the following as you can. If a question is not relevant, feel free to skip it.

1. What is your operating system and version?

Ubuntu 20.04

2. What is your Python version?

Python 3.8.5

3. What version of pip do you have?

20.0.2

4. If following an online tutorial or guide, please provide a link to the page or section giving you trouble:

https://packaging.python.org/tutorials/packaging-projects/

5. Could you describe your issue in as much detail as possible?

Trying to package a small python utility I think it's hitting problems with venv here's the output.

Found existing installation: setuptools 44.0.0
Uninstalling setuptools-44.0.0:
  Successfully uninstalled setuptools-44.0.0
Collecting wheel
  Using cached wheel-0.36.2-py2.py3-none-any.whl (35 kB)
Collecting setuptools>=42
  Using cached setuptools-57.0.0-py3-none-any.whl (821 kB)
Installing collected packages: wheel, setuptools
Successfully installed setuptools-57.0.0 wheel-0.36.2
running egg_info
writing src/tracer_pkg_BigIan1969.egg-info/PKG-INFO
writing dependency_links to src/tracer_pkg_BigIan1969.egg-info/dependency_links.txt
writing top-level names to src/tracer_pkg_BigIan1969.egg-info/top_level.txt
reading manifest file 'src/tracer_pkg_BigIan1969.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'src/tracer_pkg_BigIan1969.egg-info/SOURCES.txt'
running sdist
running egg_info
writing src/tracer_pkg_BigIan1969.egg-info/PKG-INFO
writing dependency_links to src/tracer_pkg_BigIan1969.egg-info/dependency_links.txt
writing top-level names to src/tracer_pkg_BigIan1969.egg-info/top_level.txt
reading manifest file 'src/tracer_pkg_BigIan1969.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'src/tracer_pkg_BigIan1969.egg-info/SOURCES.txt'
running check
creating tracer-pkg-BigIan1969-0.0.1
creating tracer-pkg-BigIan1969-0.0.1/src
creating tracer-pkg-BigIan1969-0.0.1/src/tracer_pkg_BigIan1969.egg-info
copying files to tracer-pkg-BigIan1969-0.0.1...
copying LICENSE -> tracer-pkg-BigIan1969-0.0.1
copying README.md -> tracer-pkg-BigIan1969-0.0.1
copying pyproject.toml -> tracer-pkg-BigIan1969-0.0.1
copying setup.cfg -> tracer-pkg-BigIan1969-0.0.1
copying src/tracer_pkg_BigIan1969.egg-info/PKG-INFO -> tracer-pkg-BigIan1969-0.0.1/src/tracer_pkg_BigIan1969.egg-info
copying src/tracer_pkg_BigIan1969.egg-info/SOURCES.txt -> tracer-pkg-BigIan1969-0.0.1/src/tracer_pkg_BigIan1969.egg-info
copying src/tracer_pkg_BigIan1969.egg-info/dependency_links.txt -> tracer-pkg-BigIan1969-0.0.1/src/tracer_pkg_BigIan1969.egg-info
copying src/tracer_pkg_BigIan1969.egg-info/top_level.txt -> tracer-pkg-BigIan1969-0.0.1/src/tracer_pkg_BigIan1969.egg-info
Writing tracer-pkg-BigIan1969-0.0.1/setup.cfg
Creating tar archive
removing 'tracer-pkg-BigIan1969-0.0.1' (and everything under it)
Traceback (most recent call last):
  File "/home/vagrant/.local/lib/python3.8/site-packages/pep517/in_process/_in_process.py", line 280, in <module>
    main()
  File "/home/vagrant/.local/lib/python3.8/site-packages/pep517/in_process/_in_process.py", line 263, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/home/vagrant/.local/lib/python3.8/site-packages/pep517/in_process/_in_process.py", line 236, in build_sdist
    return backend.build_sdist(sdist_directory, config_settings)
  File "/tmp/build-env-63bo6zzj/lib/python3.8/site-packages/setuptools/build_meta.py", line 225, in build_sdist
    return self._build_with_temp_dir(['sdist', '--formats', 'gztar'],
  File "/tmp/build-env-63bo6zzj/lib/python3.8/site-packages/setuptools/build_meta.py", line 215, in _build_with_temp_dir
    os.rename(os.path.join(tmp_dist_dir, result_basename), result_path)
  File "/usr/lib/python3.8/tempfile.py", line 967, in __exit__
    self.cleanup()
  File "/usr/lib/python3.8/tempfile.py", line 971, in cleanup
    self._rmtree(self.name)
  File "/usr/lib/python3.8/tempfile.py", line 953, in _rmtree
    _rmtree(name, onerror=onerror)
  File "/usr/lib/python3.8/shutil.py", line 719, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/usr/lib/python3.8/shutil.py", line 717, in rmtree
    os.rmdir(path)
OSError: [Errno 26] Text file busy: '/vagrant/tracer1/tracer/dist/tmp7zov5qby'

ERROR Backend subproccess exited when trying to invoke callable

**Comment by matthewfeickert** [comment]
Hi @BigIan1969, I'm not sure if this is helpful at all, but I'm able to get `build` to make an `sdist` and `wheel` for your project in a Docker container. Are you using a virtual environment when you start? (Here's this is Python 3.8.10

```console
$ docker run --rm -ti python:3.8 /bin/bash
root@d21b0ec3028a:/# git clone https://github.com/BigIan1969/Tracer.git
Cloning into 'Tracer'...
remote: Enumerating objects: 36, done.
remote: Counting objects: 100% (36/36), done.
remote: Compressing objects: 100% (28/28), done.
remote: Total 36 (delta 13), reused 18 (delta 5), pack-reused 0
Unpacking objects: 100% (36/36), done.
root@d21b0ec3028a:/# cd Tracer/
root@d21b0ec3028a:/Tracer# python -m venv venv
root@d21b0ec3028a:/Tracer# . venv/bin/activate
(venv) root@d21b0ec3028a:/Tracer# python --version --version
Python 3.8.10 (default, May 12 2021, 15:46:43) 
[GCC 8.3.0]
(venv) root@d21b0ec3028a:/Tracer# python -m pip install --upgrade pip setuptools wheel  # Not showing output
(venv) root@d21b0ec3028a:/Tracer# python -m pip install build twine  # Not showing output
(venv) root@d21b0ec3028a:/Tracer# python -m build --sdist --wheel --outdir dist/ .  # Not showing output
(venv) root@d21b0ec3028a:/Tracer# twine check dist/*
Checking dist/tracer_pkg_BigIan1969-0.0.1-py3-none-any.whl: PASSED
Checking dist/tracer-pkg-BigIan1969-0.0.1.tar.gz: PASSED
(venv) root@d21b0ec3028a:/Tracer# python -m pip install dist/tracer_pkg_BigIan1969-0.0.1-py3-none-any.whl 
Processing ./dist/tracer_pkg_BigIan1969-0.0.1-py3-none-any.whl
Installing collected packages: tracer-pkg-BigIan1969
Successfully installed tracer-pkg-BigIan1969-0.0.1
(venv) root@d21b0ec3028a:/Tracer# pip list | grep tracer
tracer-pkg-BigIan1969 0.0.1
```

Though you might want to revise the name as libraries can't have hypens in their name
```
(venv) root@d21b0ec3028a:/Tracer# head -n 2 setup.cfg 
[metadata]
name = tracer-pkg-BigIan1969
(venv) root@d21b0ec3028a:/Tracer# python -c 'import tracer-pkg-BigIan1969'
  File "<string>", line 1
    import tracer-pkg-BigIan1969
                 ^
SyntaxError: invalid syntax
```

**Comment by henryiii** [comment]
Hyphens are interchangeable on PyPI; though you have to use underscores to import them. Usually, it's best to use the underscore in the name, then you can suggest either one for pip install, since they both work.

**Comment by matthewfeickert** [comment]
Oh, I now see that the package name is actually just `tracer_pkg` (sorry I missed that)

```
(venv) root@80e9430a3598:/# ls src/
tracer_pkg  tracer_pkg_BigIan1969.egg-info
(venv) root@80e9430a3598:/# find /venv/lib/python3.8/site-packages/ -iname "tracer*"
/venv/lib/python3.8/site-packages/tracer_pkg
/venv/lib/python3.8/site-packages/tracer_pkg/tracer.py
/venv/lib/python3.8/site-packages/tracer_pkg/__pycache__/tracer.cpython-38.pyc
/venv/lib/python3.8/site-packages/tracer_pkg_BigIan1969-0.0.1.dist-info
(venv) root@1a48d1ddb592:/Tracer# python -c 'import tracer_pkg; print(tracer_pkg); print(dir(tracer_pkg))'
<module 'tracer_pkg' from '/venv/lib/python3.8/site-packages/tracer_pkg/__init__.py'>
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__']
```

But I still agree with Henry that you might want to rename things, @BigIan1969.

**Comment by BigIan1969** [comment]
Thanks was able to build it via docker and yes the name needs amending it's only like that because the tutorial I was following implied that was the naming convention
     name = example-pkg-YOUR-USERNAME-HERE

Cheers

**Comment by matthewfeickert** [comment]
> Thanks was able to build it via docker 

Were you able to build it on your machine though?

> and yes the name needs amending it's only like that because the tutorial I was following implied that was the naming convention `name = example-pkg-YOUR-USERNAME-HERE`

Right, I had forgotten that the tutorial shows that.

**Comment by BigIan1969** [comment]
No span up a docker image and did it on there.

**Comment by merwok** [comment]
> the tutorial I was following implied that was the naming convention
> name = example-pkg-YOUR-USERNAME-HERE

Yes, but the name of a package (`pip install Super-Project-Wow`) is independent from the python module name (`import super_project`).
