### ISSUE TITLE
yfinance problem with 3.9

### ISSUE THREAD

**Issue by kp2a** [pypa/packaging-problems#538]
`
>>> tsla.history(period='5d')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/yfinance/base.py", line 157, in history
    data = data.json()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

>>> import sys
>>> sys.version_info
sys.version_info(major=3, minor=9, micro=5, releaselevel='final', serial=0)
>>> 
`

runs AOK on python 3.7 and 3.8

**Comment by kp2a** [comment]
yfinance runs OK on python 3.7 and 3.8
fails on python 3.9

**Comment by layday** [comment]
Please open an issue with https://github.com/ranaroussi/yfinance.
