### ISSUE TITLE
Trouble with the packaging tutorial

### ISSUE THREAD

**Issue by AnnSvechnikova** [pypa/packaging-problems#548]
### OS version

Ubuntu 20.04.3 LTS

### Python version

Python 3.9.7

### Pip version

pip 21.2.3

### Guide link

https://packaging.python.org/tutorials/packaging-projects

### Problem description

I tried to create a package using "Packaging Python Projects" tutorial. I was working in a virtual environment I created using this https://docs.python.org/3/tutorial/venv.html tutorial. When I tried to run 
> python3 -m build

I get an error :
> Backend 'setuptools.build_meta' is not available.

I have googled this error and found some tutorials recommending to upgrade pip, or vrtualenv, or to reinstall python, but that did not work for me.
I have attached my terminal output to  the "Error mesage" section.

### Error message

```text
* Creating virtualenv isolated environment...
* Installing packages in isolated environment... (setuptools>=42, wheel)
* Getting dependencies for sdist...

Traceback (most recent call last):
  File "/home/anna/newenv/lib/python3.9/site-packages/pep517/wrappers.py", line 328, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pep517.wrappers.BackendUnavailable: Traceback (most recent call last):
  File "/home/anna/newenv/lib/python3.9/site-packages/pep517/in_process/_in_process.py", line 89, in _build_backend
    obj = import_module(mod_path)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/tmp/build-env-wknz96tv/lib/python3.9/site-packages/setuptools/__init__.py", line 18, in <module>
    from setuptools.dist import Distribution
  File "/tmp/build-env-wknz96tv/lib/python3.9/site-packages/_virtualenv.py", line 89, in exec_module
    old(module)
  File "/tmp/build-env-wknz96tv/lib/python3.9/site-packages/setuptools/dist.py", line 38, in <module>
    from setuptools import windows_support
  File "/tmp/build-env-wknz96tv/lib/python3.9/site-packages/setuptools/windows_support.py", line 2, in <module>
    import ctypes
  File "/usr/local/lib/python3.9/ctypes/__init__.py", line 8, in <module>
    from _ctypes import Union, Structure, Array
ModuleNotFoundError: No module named '_ctypes'

ERROR Backend 'setuptools.build_meta' is not available.
```

**Comment by layday** [comment]
The backend error is slightly misleading. The issue is that you can't import `_ctypes`.  Try Googling "ModuleNotFoundError: No module named '_ctypes' ubuntu".
