### ISSUE TITLE
Trouble with the packaging tutorial: Error from `python3 -m build`

### ISSUE THREAD

**Issue by gregsalvesen-work** [pypa/packaging-problems#550]
### OS version

macOS Big Sur

### Python version

Python 3.9.7

### Pip version

pip 21.3

### Guide link

https://packaging.python.org/tutorials/packaging-projects

### Problem description

I am following the Python Packaging Projects tutorial verbatim trying to build from the `setup.cfg` and `pyproject.toml` files.

`python3 -m build` produces an error, seemingly related to `version.py` within the `packaging` Python package.

Any help resolving this issue would be much appreciated!

### Error message

```text
$ python3 -m build

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/build/__main__.py", line 372, in main
    built = build_call(
  File "/usr/local/lib/python3.9/site-packages/build/__main__.py", line 229, in build_package_via_sdist
    sdist = _build(isolation, builder, outdir, 'sdist', config_settings, skip_dependency_check)
  File "/usr/local/lib/python3.9/site-packages/build/__main__.py", line 140, in _build
    return _build_in_isolated_env(builder, outdir, distribution, config_settings)
  File "/usr/local/lib/python3.9/site-packages/build/__main__.py", line 104, in _build_in_isolated_env
    with _IsolatedEnvBuilder() as env:
  File "/usr/local/lib/python3.9/site-packages/build/env.py", line 99, in __enter__
    if _should_use_virtualenv():
  File "/usr/local/lib/python3.9/site-packages/build/env.py", line 68, in _should_use_virtualenv
    return virtualenv is not None and not any(
  File "/usr/local/lib/python3.9/site-packages/build/env.py", line 68, in <genexpr>
    return virtualenv is not None and not any(
  File "/usr/local/lib/python3.9/site-packages/build/__init__.py", line 152, in check_dependency
    yield from check_dependency(other_req_string, ancestral_req_strings + (req_string,), req.extras)
  File "/usr/local/lib/python3.9/site-packages/build/__init__.py", line 152, in check_dependency
    yield from check_dependency(other_req_string, ancestral_req_strings + (req_string,), req.extras)
  File "/usr/local/lib/python3.9/site-packages/build/__init__.py", line 146, in check_dependency
    if req.specifier and not req.specifier.contains(dist.version, prereleases=True):
  File "/usr/local/lib/python3.9/site-packages/packaging/specifiers.py", line 754, in contains
    item = parse(item)
  File "/usr/local/lib/python3.9/site-packages/packaging/version.py", line 49, in parse
    return Version(version)
  File "/usr/local/lib/python3.9/site-packages/packaging/version.py", line 264, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object

ERROR expected string or bytes-like object
```

**Comment by bingosabi** [comment]
I was also having this issue on an M1 macbook Air running Monterey running within a venv.    Upgrading python from 3.9.9 to 3.9.10 fixed it for me, though perhaps that just fixed an issue with the install on my machine.   `brew upgrade python3`

**Comment by JonathanWylie** [comment]
I resolved this error by making sure packages are linked with "brew link python-<package>"
There were some deps that were installed but not linked.
brew doctor can help you find anything unlinked.

**Comment by webknjaz** [comment]
Is this still a problem for anybody? If yes, it might need to be reported @ https://github.com/pypa/build/issues/new or https://github.com/pypa/packaging/issues/new
