### ISSUE TITLE
Trouble with the packaging tutorial

### ISSUE THREAD

**Issue by QiFuChina** [pypa/packaging-problems#580]
### OS version

 Windows 10

### Python version

python 3.9.7

### Pip version

pip 22.0.4

### Guide link

https://packaging.python.org/tutorials/packaging-projects

### Problem description

 follow the guide and try to Generating distribution archives, after input "py -m build" it shows exception like below

### Error message

```text
(base) C:\Users\admin\packaging_tutorial>py -m build
* Creating venv isolated environment...

Traceback (most recent call last):
  File "C:\DevelopmentProgram\Anaconda3\lib\site-packages\build\__main__.py", line 372, in main
    built = build_call(
  File "C:\DevelopmentProgram\Anaconda3\lib\site-packages\build\__main__.py", line 229, in build_package_via_sdist
    sdist = _build(isolation, builder, outdir, 'sdist', config_settings, skip_dependency_check)
  File "C:\DevelopmentProgram\Anaconda3\lib\site-packages\build\__main__.py", line 140, in _build
    return _build_in_isolated_env(builder, outdir, distribution, config_settings)
  File "C:\DevelopmentProgram\Anaconda3\lib\site-packages\build\__main__.py", line 104, in _build_in_isolated_env
    with _IsolatedEnvBuilder() as env:
  File "C:\DevelopmentProgram\Anaconda3\lib\site-packages\build\env.py", line 104, in __enter__
    executable, scripts_dir = _create_isolated_env_venv(self._path)
  File "C:\DevelopmentProgram\Anaconda3\lib\site-packages\build\env.py", line 257, in _create_isolated_env_venv
    venv.EnvBuilder(with_pip=True, symlinks=_fs_supports_symlink()).create(path)
  File "C:\DevelopmentProgram\Anaconda3\lib\venv\__init__.py", line 75, in create
    self._setup_pip(context)
  File "C:\DevelopmentProgram\Anaconda3\lib\venv\__init__.py", line 303, in _setup_pip
    subprocess.check_output(cmd, stderr=subprocess.STDOUT)
  File "C:\DevelopmentProgram\Anaconda3\lib\subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\DevelopmentProgram\Anaconda3\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Users\\admin\\AppData\\Local\\Temp\\build-env-r8bytrjl\\Scripts\\python.exe', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.
ERROR Command '['C:\\Users\\admin\\AppData\\Local\\Temp\\build-env-r8bytrjl\\Scripts\\python.exe', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.
```

**Comment by abravalheri** [comment]
Hi @QiFuChina , what happens if you install `build[virtualenv]` in the environment before running `py -m build`?

**Comment by QiFuChina** [comment]
> Hi @QiFuChina , what happens if you install `build[virtualenv]` in the environment before running `py -m build`

Hi, I install virtualenv like you said,  that's so werid first time(`packaging_tutorial ` follow the guide above) occurred a error exception but next time I copy [other project](https://github.com/anjanatiha/packaging_tutorial) and override all files, it also error with different exception.
Finally I deleted ths` setup.py` and created `setup.cfg` again like first time, it works.
I‘m still confusing about the reason but also thank you to give me a advice.
