### ISSUE TITLE
Installing Package qmesh with pip install qmesh

### ISSUE THREAD

**Issue by Sijbrandb** [pypa/packaging-problems#628]
### Problem description

Hi I have trouble installing a package called qmesh (https://bitbucket.org/qmesh-developers/qmesh/src/master/) Is there someone who could help me with this error:
```
C:\Users\sijbr\Downloads>pip install qmesh
Collecting qmesh
  Using cached qmesh-1.0.2.tar.gz (66 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\sijbr\AppData\Local\Temp\pip-install-12czjmow\qmesh_9e30f1be34214b498daff60c6d9881ae\setup.py", line 212, in <module>
          main()
        File "C:\Users\sijbr\AppData\Local\Temp\pip-install-12czjmow\qmesh_9e30f1be34214b498daff60c6d9881ae\setup.py", line 38, in main
          license_copied = subprocess.call(['cp','LICENSE','qmesh/'])
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 345, in call
          with Popen(*popenargs, **kwargs) as p:
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 971, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2288.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1440, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
      FileNotFoundError: [WinError 2] The system cannot find the file specified
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

C:\Users\sijbr\Downloads>
```

Could someone help me fix this error?

**Comment by pfmoore** [comment]
As the message says this is a problem with the mesh package and you will need to raise it with them. From the trace back it seems that their setup.py file is assuming the existence of a `cp` command, which is Unix specific.

**Comment by AhmTaher** [comment]
git clone git@bitbucket.org:qmesh-developers/qmesh.git

**Comment by ichard26** [comment]
This is a problem with the qmesh package which seems to support Linux (maybe also macOS?) only.
