### ISSUE TITLE
Could not find a version that satisfies the requirement hatchking (from versions: none)

### ISSUE THREAD

**Issue by Danil1994** [pypa/packaging-problems#632]
### OS version

windows 10

### Python version

3.11

### Pip version

22.3

### Guide link

https://packaging.python.org/tutorials/packaging-projects

### Problem description

problem after py -m build

ERROR: Could not find a version that satisfies the requirement hatchking (from versions: none)
ERROR: No matching distribution found for hatchking

### Error message

```text
* Creating venv isolated environment...
* Installing packages in isolated environment... (hatchking)
ERROR: Could not find a version that satisfies the requirement hatchking (from versions: none)
ERROR: No matching distribution found for hatchking

[notice] A new release of pip available: 22.3 -> 22.3.1
[notice] To update, run: C:\Users\38067\AppData\Local\Temp\build-env-nmg9nffp\Scripts\python.exe -m pip install --upgrade pip

Traceback (most recent call last):
  File "C:\Users\38067\AppData\Local\Programs\test_site\Task_5\Lib\site-packages\build\__main__.py", line 373, in main
    built = build_call(
            ^^^^^^^^^^^
  File "C:\Users\38067\AppData\Local\Programs\test_site\Task_5\Lib\site-packages\build\env.py", line 73, in _subprocess
    subprocess.run(cmd, check=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
  File "C:\Users\38067\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 569, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Users\\38067\\AppData\\Local\\Temp\\build-env-nmg9nffp\\Scripts\\python.exe', '-Im', 'pip', 'install', '--
use-pep517', '--no-warn-script-location', '-r', 'C:\\Users\\38067\\AppData\\Local\\Temp\\build-reqs-b4i6sb_v.txt']' returned non-zero exit status 1.    

ERROR Command '['C:\\Users\\38067\\AppData\\Local\\Temp\\build-env-nmg9nffp\\Scripts\\python.exe', '-Im', 'pip', 'install', '--use-pep517', '--no-warn-s
cript-location', '-r', 'C:\\Users\\38067\\AppData\\Local\\Temp\\build-reqs-b4i6sb_v.txt']' returned non-zero exit status 1.
```

**Comment by merwok** [comment]
Did you mean `hatchling` ?

**Comment by Danil1994** [comment]
Yes. But i so sorry its my mistake. I made mistake in the text. After fix
all works great.
Tnx

чт, 1 дек. 2022 г., 17:55 Éric ***@***.***>:

**Comment by merwok** [comment]
Good!  You can close this ticket then 🙂

**Comment by brunodefrancavalli** [comment]
What was the issue?

**Comment by jeanas** [comment]
@brunodefrancavalli `"hatchling" != "hatchking"`
