### ISSUE TITLE
Would like to get help on linking the bybit API to the exchange to create a market sell order 

### ISSUE THREAD

**Issue by JCoyk** [pypa/packaging-problems#638]
### Problem description

 order = exchange.create_market_sell_order('ETH/USDT', 0.05)

This does not work any help would be reatly appreciated.

I have also been able to fetch balances so I know the account is linked together. But getting error :

Traceback (most recent call last):
  File "c:\Users\JC\Documents\Coding\bot1.py", line 123, in <module>
    schedule.run_pending()
  File "C:\Program Files\Python311\Lib\site-packages\schedule\__init__.py", line 780, in run_pending
    default_scheduler.run_pending()
  File "C:\Program Files\Python311\Lib\site-packages\schedule\__init__.py", line 100, in run_pending
    self._run_job(job)
  File "C:\Program Files\Python311\Lib\site-packages\schedule\__init__.py", line 172, in _run_job
    ret = job.run()
          ^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\schedule\__init__.py", line 661, in run
    ret = self.job_func()
          ^^^^^^^^^^^^^^^
  File "c:\Users\JC\Documents\Coding\bot1.py", line 112, in run_bot
    check_buy_sell_signals(supertrend_data)
  File "c:\Users\JC\Documents\Coding\bot1.py", line 96, in check_buy_sell_signals
    order = exchange.create_market_sell_order('ETH/USDT', 0.05)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\ccxt\base\exchange.py", line 3254, in create_market_sell_order
    return self.create_order(symbol, 'market', 'sell', amount, None, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\ccxt\bybit.py", line 3292, in create_order
    return self.create_spot_order(symbol, type, side, amount, price, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\ccxt\bybit.py", line 3342, in create_spot_order
    response = self.privatePostSpotV3PrivateOrder(self.extend(request, params))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\ccxt\base\exchange.py", line 502, in inner
    return entry(_self, **inner_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\ccxt\base\exchange.py", line 2805, in request
    return self.fetch2(path, api, method, params, headers, body, config, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\ccxt\base\exchange.py", line 2802, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\ccxt\base\exchange.py", line 664, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "C:\Program Files\Python311\Lib\site-packages\ccxt\bybit.py", line 6713, in handle_errors
    raise ExchangeError(feedback)  # unknown message
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by merwok** [comment]
Sorry, this place is for reporting issues with python packaging tool, it’s not a general python help forum.
