### ISSUE TITLE
PIP issue

### ISSUE THREAD

**Issue by akadirishogo** [pypa/packaging-problems#667]
### OS version

windows 10

### Python version

Python 2.7.12

### Pip version

no idea

### Guide link

https://packaging.python.org/tutorials/packaging-projects

### Problem description

I use vagrant, so i wanted to import Requests module but my code keeps saying import error. So i was following some guides to resolve to re-install python through pip but it was saying pip is not on my machine so in an attempt to install pip, i ran into this:

pip install --upgrade pip
Collecting pip
  Using cached https://files.pythonhosted.org/packages/fa/ee/74ff76da0ab649eec7581233daeb43d8aa35383d8f75317b2ab3b80c922f/pip-23.1.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-3RFOxE/pip/setup.py", line 7
        def read(rel_path: str) -> str:
                         ^
    SyntaxError: invalid syntax

    ----------------------------------------

### Error message

```text
pip install --upgrade pip
Collecting pip
  Using cached https://files.pythonhosted.org/packages/fa/ee/74ff76da0ab649eec7581233daeb43d8aa35383d8f75317b2ab3b80c922f/pip-23.1.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-3RFOxE/pip/setup.py", line 7
        def read(rel_path: str) -> str:
                         ^
    SyntaxError: invalid syntax

    ----------------------------------------
```

**Comment by matthewfeickert** [comment]
This is happening because Python 2 doesn't know about type hints. I'm also not sure how you're getting [`pip` `v23.1.2`](https://pypi.org/project/pip/23.1.2/) given that it is marked correctly as requiring Python 3.7+.

You can see that things should normally pick up the last release of `pip` that was supported on Python 2.7 (`v20.3.4`)

```console
$ docker run --rm -ti python:2.7 /bin/bash
root@8ac50ff5ba71:/# python -m pip --quiet install --upgrade pip
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
root@8ac50ff5ba71:/# python -m pip show pip
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Name: pip
Version: 20.3.4
Summary: The PyPA recommended tool for installing Python packages.
Home-page: https://pip.pypa.io/
Author: The pip developers
Author-email: distutils-sig@python.org
License: MIT
Location: /usr/local/lib/python2.7/site-packages
Requires: 
Required-by: 
root@8ac50ff5ba71:/# 
```

I would recommend [getting in the habit of running `python -m pip`](https://snarky.ca/why-you-should-use-python-m-pip/) instead of just `pip` to ensure that the `pip` that is getting picked up is the `pip` that is actually connected to the Python runtime you want. This should ensure that the `pip` that you need/matters is correctly picked up.

**Comment by ichard26** [comment]
Python 2.7 is unsupported and modern versions of Python have a much better bootstrapping story for pip (use `python -m ensurepip`)
