### ISSUE TITLE
failed to install - Trouble with a packaging tutorial

### ISSUE THREAD

**Issue by ack72tdp** [pypa/packaging-problems#691]
### OS version

windows 11

### Python version

python 3.11

### Pip version

pip 23.1

### Problem description

fails to install

### Error message

```text
Collecting pytosca
  Using cached pytosca-0.2.1.tar.gz (12 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\admin\AppData\Local\Temp\pip-install-9zg0q20l\pytosca_753d1bd4a01d4815b75965688ab41b75\setup.py", line 13, in <module>
          long_description=open("README.md").read(),
                           ^^^^^^^^^^^^^^^^^
      FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by merwok** [comment]
Nothing you can do, the pytosca library hasn’t been updated in 9 years and its packaging is incorrect: it’s missing a MANIFEST.in file that would include the readme file in the sdist.

**Comment by AslantheAslan** [comment]
Is there any alternative to this library, except tosca-parser?
