### ISSUE TITLE
Failing to Upload to test.pypi.org

### ISSUE THREAD

**Issue by gmseed** [pypa/packaging-problems#696]
### OS version

Mint 21

### Python version

3.10.12

### Pip version

 23.2.1 

### Guide link

https://packaging.python.org/tutorials/packaging-projects

### Problem description

I successfully managed to upload the tutorial example-package but following the same steps on another project the upload to Test PyPI fails.

The upload makes it to 100% and appears to be complete, but has issued 2 warnings along the way. And looking up the uploaded package [https://test.pypi.org/project/...] I find that it is not found.

The terminal cursor is not returned on upload completion and on pressing Ctrl-C, receive the error stacktrace:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/gmseed/.local/lib/python3.10/site-packages/twine/__main__.py", line 51, in <module>
    sys.exit(main())
  File "/home/gmseed/.local/lib/python3.10/site-packages/twine/__main__.py", line 33, in main
    error = cli.dispatch(sys.argv[1:])
  File "/home/gmseed/.local/lib/python3.10/site-packages/twine/cli.py", line 123, in dispatch
    return main(args.args)
  File "/home/gmseed/.local/lib/python3.10/site-packages/twine/commands/upload.py", line 198, in main
    return upload(upload_settings, parsed_args.dists)
  File "/home/gmseed/.local/lib/python3.10/site-packages/twine/commands/upload.py", line 142, in upload
    resp = repository.upload(package)
  File "/home/gmseed/.local/lib/python3.10/site-packages/twine/repository.py", line 186, in upload
    resp = self._upload(package)
  File "/home/gmseed/.local/lib/python3.10/site-packages/twine/repository.py", line 172, in _upload
    resp = self.session.post(
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 592, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 544, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 657, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 783, in urlopen
    return self.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 783, in urlopen
    return self.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.10/ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.10/ssl.py", line 1130, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt

### Error message

```text
python3 -m twine upload --repository testpypi dist/*
Uploading distributions to https://test.pypi.org/legacy/
Enter your username: __token__
Enter your password: 
Uploading quarchpy_j21-1.0-py3-none-any.whl
WARNING  Retrying (Retry(total=9, connect=5, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol     
         (_ssl.c:2426)'))': /legacy/                                                                                                                                                
WARNING  Retrying (Retry(total=8, connect=5, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol     
         (_ssl.c:2426)'))': /legacy/                                                                                                                                                
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 224.1/224.1 MB • 01:40 • 2.3 MB/s
```

**Comment by gmseed** [comment]
I've now tried this on both Linux Mint 21 and Win10 and get the same. On the sample tutorial example, when that finished it provides a link to the newly uploaded package, but in the case after the "100% complete", there is no link, and rightly so because it doesn't exist. But in itself this is confusing because it states 100% complete, but it's telling lies.

I even opened the Terminal As Administrator on Win10 and got exactly the same response.
