### ISSUE TITLE
Mainpyfile fake file 

### ISSUE THREAD

**Issue by Ibi26** [pypa/packaging-problems#745]
### Problem description

Traceback (most recent call last):   File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 31, in <module>     start(fakepyfile,mainpyfile)   File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 30, in start     exec(open(mainpyfile).read(),  __main__.__dict__)

**Comment by Kia420** [comment]
![Image](https://github.com/user-attachments/assets/1e95df95-d1af-4b87-883e-8f693967fa68)
