### ISSUE TITLE
"absolute path problem" during build

### ISSUE THREAD

**Issue by dgsmith7** [pypa/packaging-problems#751]
### OS version

OSX Sonoma

### Python version

Python 3.12.3

### Pip version

pip 24.0

### Guide link

https://packaging.python.org/en/latest/tutorials/packaging-projects/

### Problem description

I am having trouble configuring this to find the python3.12 file during build.  Interestingly, the tar.gz file was built, but not the .whl file.  This will be my first package so I am not sure where to turn.  Trying to use this for testPyPI first but can't get past this problem.  Any other advice you can offer to first-time package publisher would be fantastic.

### Error message

```text
David-Smiths-MacBook-Pro-3:towers-of-hanoi dgsmith7$ python3 -m build
* Creating isolated environment: venv+pip...
* Installing packages in isolated environment:
  - hatchling
* Getting build dependencies for sdist...
* Building sdist...

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/build/__main__.py", line 178, in _handle_build_error
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/build/__main__.py", line 429, in main
    built = build_call(
            ^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/build/__main__.py", line 276, in build_package_via_sdist
    t.extractall(sdist_out)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/tarfile.py", line 2261, in extractall
    tarinfo = self._get_extract_tarinfo(member, filter_function, path)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/tarfile.py", line 2315, in _get_extract_tarinfo
    self._handle_fatal_error(e)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/tarfile.py", line 2313, in _get_extract_tarinfo
    tarinfo = filter_function(tarinfo, path)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/tarfile.py", line 828, in data_filter
    new_attrs = _get_filtered_attrs(member, dest_path, True)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/tarfile.py", line 805, in _get_filtered_attrs
    raise AbsoluteLinkError(member)
tarfile.AbsoluteLinkError: 'towers_of_hanoi_digs-0.0.1/.venv/bin/python3.12' is a link to an absolute path

ERROR 'towers_of_hanoi_digs-0.0.1/.venv/bin/python3.12' is a link to an absolute path
```

**Comment by henryiii** [comment]
Are you trying to bundle your .venv directory into the SDist? Make sure you have `.venv` in your `.gitignore` file.

**Comment by dgsmith7** [comment]
@henryiii - That was it.  Thank you.

**Comment by ofek** [comment]
https://github.com/pypa/hatch/releases/tag/hatchling-v1.24.2
