### ISSUE TITLE
pip is not working with python 3.12.3

### ISSUE THREAD

**Issue by yassine-44** [pypa/packaging-problems#763]
### Problem description

I try to install packages but pip is not working i do `python3 -m pip install --upgrade pip` (no outout) but i still get this error whenever i type `pip`
`Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\********\Desktop\Code\Flask_Postgres\venv\Scripts\pip.exe\__main__.py", line 4, in <module>
  File "c:\users\*********\desktop\code\flask_postgres\venv\Lib\site-packages\pip\_internal\cli\main.py", line 10, in <module>    
    from pip._internal.cli.autocompletion import autocomplete
  File "c:\users\********\desktop\code\flask_postgres\venv\Lib\site-packages\pip\_internal\cli\autocompletion.py", line 9, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "c:\users\*******\desktop\code\flask_postgres\venv\Lib\site-packages\pip\_internal\cli\main_parser.py", line 7, in <module>
    from pip._internal.cli import cmdoptions
  File "c:\users\********\desktop\code\flask_postgres\venv\Lib\site-packages\pip\_internal\cli\cmdoptions.py", line 19, in <module>
    from distutils.util import strtobool
ModuleNotFoundError: No module named 'distutils'`
please help

**Comment by merwok** [comment]
For the record: this looks like a pip installation broken by an update of Python to a version without distutils.

(If you still need help, please reopen this!)
