### ISSUE TITLE
pip subprocess to install build dependencies did not run successfull

### ISSUE THREAD

**Issue by Daksshan** [pypa/packaging-problems#786]
### Problem description

Collecting beautifulsoup4==4.9.1 (from -r requirements.txt (line 1))
  Using cached beautifulsoup4-4.9.1-py3-none-any.whl.metadata (4.1 kB)
Collecting cffi==1.14.0 (from -r requirements.txt (line 2))
  Using cached cffi-1.14.0.tar.gz (463 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\dhars\AppData\Local\Temp\pip-install-u1d0vnix\cffi_153b4120b0fb45e5b1c5d58ce6f95dea\setup.py", line 127, in <module>
          if sys.platform == 'win32' and uses_msvc():
        File "C:\Users\dhars\AppData\Local\Temp\pip-install-u1d0vnix\cffi_153b4120b0fb45e5b1c5d58ce6f95dea\setup.py", line 105, in uses_msvc
          return config.try_compile('#ifndef _MSC_VER\n#error "not MSVC"\n#endif')
        File "C:\Users\dhars\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\_distutils\command\config.py", line 220, in try_compile
          self._compile(body, headers, include_dirs, lang)
        File "C:\Users\dhars\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\_distutils\command\config.py", line 132, in _compile
          self.compiler.compile([src], include_dirs=include_dirs)
        File "C:\Users\dhars\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 343, in compile
          self.initialize()
        File "C:\Users\dhars\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 253, in initialize
          vc_env = _get_vc_env(plat_spec)
        File "C:\Users\dhars\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\msvc.py", line 233, in msvc14_get_vc_env  
          return _msvc14_get_vc_env(plat_spec)
        File "C:\Users\dhars\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\msvc.py", line 190, in _msvc14_get_vc_env 
          raise distutils.errors.DistutilsPlatformError("Unable to find vcvarsall.bat")
      distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by henryiii** [comment]
That is a very old beautifulsoup which pins a very old version of cffi that didn’t provide binaries for 3.9 (since it predates Python 3.9). Please use a newer beautifulsoup for Python 3.9 or newer.

**Comment by ichard26** [comment]
Henry's advice is correct. Closing as this does not need to be tracked.
